### ISSUE TITLE
用webview打开一个网页的时候,怎么能带着cookie?

### ISSUE THREAD

**Issue by suntsh** [lxn/walk#100]
需要在打开一个网页的时候带着,前面登陆网站的cookies,保持用户的登陆状态,怎么才能在webview里面带着cookies呢?

**Comment by dzcpy** [comment]
找到解决方法了吗？

**Comment by suntsh** [comment]
没有啊，你还在用这个库吗？



bigbet@126.com
 
发件人： dzcpy
发送时间： 2020-08-29 01:11
收件人： lxn/walk
抄送： suntsh; State change
主题： Re: [lxn/walk] 用webview打开一个网页的时候,怎么能带着cookie? (#100)
找到解决方法了吗？

**Comment by dzcpy** [comment]
不用了，我换 aardio 了，非常简单

**Comment by jiusanzhou** [comment]
1.  可以打开IE登陆

**Comment by jiusanzhou** [comment]
有2种方式可以试试：
1. 登陆时打开IE进行登陆
2. 在URL后面带上Cookie，然后JS去设置Cookie，前提是页面是自己的
