### ISSUE TITLE
Let toolbar buttons have both text and image

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#113]
toolbar.go in walk package line 268:

if action.image == nil {
	*style |= win.BTNS_SHOWTEXT
}

If image is not set then toolbar has text. Otherwise text is not shown. I prefer to have some or all toolbar buttons with text and image. 

Another issue is shortcut shown on the toolbar button. Highly unusual. Code that does it is in the same toolbar.go lines around 290:

if s := action.shortcut; s.Key != 0 {
		actionText = fmt.Sprintf("%s (%s)", action.Text(), s.String())
	} else {
		actionText = action.Text()
	}

Is there any way to get some toolbar buttons show text and image, and allow the option of not showing keyboard shortcuts on buttons?

**Comment by lxn** [comment]
Please try the most recent stuff.
