### ISSUE TITLE
Ability to set negative conditions

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#114]
I have registered condition isRunning like so:
MustRegisterCondition("isRunning", isRunning)

It works fine enabling some Actions. But does not allow to have negative syntax such as:

Action{
	AssignTo:    &runAction,
	Text:        "Run All",
	Image:       runImage,
	Enabled:     Bind("isRunning == false"),
	Shortcut:    Shortcut{Key: walk.KeyF5},
	OnTriggered: mw.runAction_Triggered,
},

None seems to be possible :
Bind("isRunning == false")
Bind("!isRunning")
Bind("not isRunning")

I find both databinding and action based binding to be one of the finest features of Walk framework.
I found a workaround for the issue above by having only positive Conditions and switch few of them on/off in special function. But having ability to set negated expressions in Bind would help.

**Comment by lxn** [comment]
Fixed by https://github.com/lxn/walk/commit/bf6f749b94265e032162d0c26f7f39b015967ee3
