### ISSUE TITLE
Progress bar example does not show progress bar

### ISSUE THREAD

**Issue by DannyBen** [lxn/walk#125]
In the [progressindicator example](https://github.com/lxn/walk/tree/master/examples/progressindicator), the only thing I see are the buttons. No matter what I press, there is no progress bar (and I do see progress logged in the console).

For comparison, the small example in Issue #76 is working properly.

Windows 8.1 • go version go1.3.1 windows/amd64

**Comment by jda-iocom** [comment]
It's not a progressbar example, it's a progressindicator example. This means the icon for the running app is the thing that shows the progress.

**Comment by DannyBen** [comment]
A lot of time has passed since I forgot what was this all about... :)
Thanks for the reply, but I believe this ticket can be closed.
