### ISSUE TITLE
Fails to run after upgrade to go1.4

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#134]
Number of examples fail to run after upgrading to go1.4 under Windows GOARCH=386. They work on Windows GOARCH=amd64. Once you downgrade into go1.3 everything works fine.

There is typical stack trace once you use go1.4 or go1.4.1 and try to run it after build targeting 386:

C:/_godev/src/github.com/lxn/walk/error.go:79 (0x45ea11)
        newErr: return &Error{message: message, stack: debug.Stack()}
C:/_godev/src/github.com/lxn/walk/error.go:83 (0x45eb50)
        newError: return processError(newErr(message))
C:/_godev/src/github.com/lxn/walk/tooltip.go:115 (0x485c67)
        (*ToolTip).AddTool: return newError("TTM_ADDTOOL failed")
C:/_godev/src/github.com/lxn/walk/widget.go:106 (0x48a31e)
        (*WidgetBase).init: if err := globalToolTip.AddTool(wb); err != nil {
C:/_godev/src/github.com/lxn/walk/window.go:396 (0x48cc26)
        InitWindow: if err := wb.init(widget); err != nil {
C:/_godev/src/github.com/lxn/walk/widget.go:85 (0x48a16b)
        InitWidget: if err := InitWindow(widget, parent, className, style|win.WS_CHILD, exStyle); err != nil {
C:/_godev/src/github.com/lxn/walk/composite.go:31 (0x45a910)
        newCompositeWithStyle: win.WS_EX_CONTROLPARENT); err != nil {
C:/_godev/src/github.com/lxn/walk/composite.go:39 (0x45aa21)
        NewComposite: return newCompositeWithStyle(parent, 0)
C:/_godev/src/github.com/lxn/walk/form.go:78 (0x4600a3)
        (*FormBase).init: if fb.clientComposite, err = NewComposite(form); err != nil {
C:/_godev/src/github.com/lxn/walk/window.go:388 (0x48cb89)
        InitWindow: if err := fb.init(form); err != nil {
C:/_godev/src/github.com/lxn/walk/mainwindow.go:37 (0x4691e9)
        NewMainWindow: win.WS_EX_CONTROLPARENT); err != nil {
C:/_godev/src/github.com/lxn/walk/declarative/mainwindow.go:37 (0x4c38c5)
        MainWindow.Create: w, err := walk.NewMainWindow()
C:/_godev/src/_desktop/mapper/mapper.go:422 (0x403577)
        RunMainWindow: }.Create()); err != nil {
C:/_godev/src/_desktop/mapper/mapper.go:123 (0x4011d3)
        main: if err := RunMainWindow(false); err != nil {
c:/go/src/runtime/proc.go:63 (0x4181dc)
        main: main_main()
c:/go/src/runtime/asm_386.s:2287 (0x4385c1)
        goexit:

Problem instantly disappears if you downgrade into go1.3 and perform 
go build -a

This is somehow only GOARCH=386 problem.
I hope this can be fixed.

**Comment by wrzech** [comment]
I have seen a similar failure in my walk application after upgrading to go 1.4.  Reverting to 1.3.3 windows/amd64 solves problem.  I observe random program exits just resizing windows.  Or adding more than one item to a GroupBox causes MainWindow.Create to fail.

**Comment by tadvi** [comment]
Looks like walk has been abandoned. Anyone willing to clone and patch it? I would chip in with help.

**Comment by lxn** [comment]
Sorry for the lack of updates.

I'm clueless on how to fix this issue. Probably a lot of effort required, see https://github.com/andlabs/ui/issues/75 for another project bitten by this.

I maintain several production applications that depend on walk, so I would certainly be happy to have it work on new Go releases.

**Comment by tadvi** [comment]
That's not good. I have tons of apps that depend on walk, and number of them are in production.
Go team is making a lot of changes for 1.5 release. My only hope at this point is that Go 1.5 will make walk lib work again.

**Comment by DoraemonYu** [comment]
Hi~ dears.
After upgrading to go 1.4, I also have a similar failure in my walk application,and the same as the sample from walk.
At now, I am keeping using the older version of go(1.3).

After debuging the issue, I still have no more idea.So sorry.
I am paying attention to the progress of this issue,and  looking forward to be resolved.

**Comment by lxn** [comment]
Some news on this subject.

Got an idea on how to repro this outside of walk. Maybe it is another issue, but the following code works on Go 1.3.3, but not on 1.4.2:

```Go
package main

import (
	"fmt"
	"syscall"
	"unsafe"
)

var (
	libuser32        syscall.Handle
	enumWindows      uintptr
	enumChildWindows uintptr

	enumWindowsCallback      uintptr
	enumChildWindowsCallback uintptr
)

func EnumWindows(lpEnumFunc uintptr, lParam unsafe.Pointer) bool {
	//	defer escape(unsafe.Pointer(lParam))

	ret, _, _ := syscall.Syscall(enumWindows, 2,
		lpEnumFunc,
		uintptr(lParam),
		0)

	return ret != 0
}

func EnumChildWindows(hWndParent syscall.Handle, lpEnumFunc uintptr, lParam unsafe.Pointer) bool {
	ret, _, _ := syscall.Syscall(enumChildWindows, 3,
		uintptr(hWndParent),
		lpEnumFunc,
		uintptr(lParam))

	return ret != 0
}

var escapedPtr unsafe.Pointer

func escape(ptr unsafe.Pointer) {
	escapedPtr = ptr
	escapedPtr = nil
}

type Foo struct {
	bar [1000]float64
}

func main() {
	libuser32, _ = syscall.LoadLibrary("user32.dll")
	enumWindows, _ = syscall.GetProcAddress(libuser32, "EnumWindows")
	enumChildWindows, _ = syscall.GetProcAddress(libuser32, "EnumChildWindows")

	enumWindowsCallback = syscall.NewCallback(EnumWindowsCallback)
	enumChildWindowsCallback = syscall.NewCallback(EnumChildWindowsCallback)

	var foo Foo

	for i := range foo.bar {
		foo.bar[i] = 777
	}

	EnumWindows(enumWindowsCallback, unsafe.Pointer(&foo))

	fmt.Println(foo.bar)
}

func EnumWindowsCallback(hwnd syscall.Handle, lParam unsafe.Pointer) uintptr {
	fmt.Printf("EnumWindowsCallback - hwnd: %v, lParam: %v\n", hwnd, len((*Foo)(unsafe.Pointer(lParam)).bar))

	var foo Foo

	EnumChildWindows(hwnd, enumChildWindowsCallback, lParam)

	fmt.Println(len(foo.bar))

	return 1
}

func EnumChildWindowsCallback(hwnd syscall.Handle, lParam unsafe.Pointer) uintptr {
	foo1 := (*Foo)(unsafe.Pointer(lParam))

	fmt.Printf("EnumChildWindowsCallback - hwnd: %v, lParam: %v\n", hwnd, len(foo1.bar))

	var foo2 Foo

	for i := range foo1.bar {
		foo1.bar[i] += float64(i)
	}

	fmt.Println(foo1.bar)

	fmt.Println(len(foo2.bar))

	return 1
}
```
The problem seems to be the escape analysis of the compiler which stops at any conversion of a pointer to `uintptr`, leaving some values on the stack, despite walk handing out pointers to them to the Windows api. Then on some function call the runtime determines that the stack is exhausted and since Go 1.4 does not add another segment to the stack, but creates a new stack and copies the old one over. But Windows still has those pointers to the old stack, now pointing to some random garbage.

If you uncomment the deferred call to `escape` in `EnumWindows`, it works on Go 1.4.2 as well.

So I went ahead and added such calls to all functions in the win package, for every pointer parameter. Also I tried to find and instrument all occurrences in walk where a pointer is converted to `uintptr`. Sadly it did not help a bit. The examples that failed before still fail  with the same stack traces.

If anybody would like to check those changes out, let me know.

**Comment by tadvi** [comment]
lxn: Thank you for looking into it. Can you report this into go-nuts forum? So at least in version 1.5 Go team would fix how escape analysis works.

**Comment by lxn** [comment]
Pushed escape branches to both win and walk repos, if someone wants to have a look.

**Comment by lxn** [comment]
Great news!

Just a couple minutes ago, Go 1.5 beta 1 has been released and guess what. It seems to fix this problem. :-)

**Comment by tadvi** [comment]
Awesome. Looking forward to 1.5.

**Comment by DoraemonYu** [comment]
~\(≧▽≦)/~ Wonderful ! That's a Good news.
I will try to update it as well later.

**Comment by lxn** [comment]
Cheered too soon :-(

Crashes still happen, but not as early as with Go 1.4.x.

**Comment by lxn** [comment]
Wow. It seems walk doesn't work reliably with ANY Go version. At least with 1.2.2, 1.3.2, 1.3.3 it doesn't work any better than with 1.5 beta 1. At some point, when a program has created enough garbage, it will randomly crash.

**Comment by DoraemonYu** [comment]
I had try it last night, and it's a good result to me.
~\(≧▽≦)/~  YES,It seems to be fixed!

I upgrad the go version to "1.5 Beta1  windows/386".
Then,my walk application and the sample from walk works both,without crash.

Just try it please,It maybe solved with your application as well.
Hoping revice more good result from all of you :)

**Comment by lxn** [comment]
As mentioned [here](https://github.com/lxn/walk/issues/139#issuecomment-122796149), things have cleared up, closing this issue.
