### ISSUE TITLE
examples\listbox examples\notifyicon  for  go 1.4.2  run error    

### ISSUE THREAD

**Issue by suntsh** [lxn/walk#139]
2015/06/26 19:15:21 CreateWindowEx

Stack:
C:/G/src/github.com/lxn/walk/error.go:79 (0x440151)
        newErr: return &Error{message: message, stack: debug.Stack()}
C:/G/src/github.com/lxn/walk/error.go:83 (0x440290)
        newError: return processError(newErr(message))
C:/G/src/github.com/lxn/walk/error.go:95 (0x44048e)
        lastError: return newError(win32FuncName)
C:/G/src/github.com/lxn/walk/window.go:364 (0x45adf1)
        InitWindow: return lastError("CreateWindowEx")
C:/G/src/github.com/lxn/walk/widget.go:94 (0x45860b)
        InitWidget: if err := InitWindow(widget, parent, className, style|win.WS
_CHILD, exStyle); err != nil {
C:/G/src/github.com/lxn/walk/composite.go:31 (0x43c910)
        newCompositeWithStyle: win.WS_EX_CONTROLPARENT); err != nil {
C:/G/src/github.com/lxn/walk/composite.go:39 (0x43ca21)
        NewComposite: return newCompositeWithStyle(parent, 0)
C:/G/src/github.com/lxn/walk/form.go:78 (0x4417e3)
        (*FormBase).init: if fb.clientComposite, err = NewComposite(form); err !
= nil {
C:/G/src/github.com/lxn/walk/window.go:388 (0x45b019)
        InitWindow: if err := fb.init(form); err != nil {
C:/G/src/github.com/lxn/walk/mainwindow.go:37 (0x445879)
        NewMainWindow: win.WS_EX_CONTROLPARENT); err != nil {
C:/G/src/github.com/lxn/walk/examples/notifyicon/notifyicon.go:18 (0x401028)
        main: mw, err := walk.NewMainWindow()
c:/go/src/runtime/proc.go:63 (0x41061c)
        main: main_main()
c:/go/src/runtime/asm_386.s:2287 (0x430b71)

2015/06/26 19:16:24 TTM_ADDTOOL failed

Stack:
C:/G/src/github.com/lxn/walk/error.go:79 (0x467e71)
        newErr: return &Error{message: message, stack: debug.Stack()}
C:/G/src/github.com/lxn/walk/error.go:83 (0x467fb0)
        newError: return processError(newErr(message))
C:/G/src/github.com/lxn/walk/tooltip.go:115 (0x484d67)
        (*ToolTip).AddTool: return newError("TTM_ADDTOOL failed")
C:/G/src/github.com/lxn/walk/widget.go:115 (0x4884ee)
        (*WidgetBase).init: if err := globalToolTip.AddTool(wb); err != nil {
C:/G/src/github.com/lxn/walk/window.go:396 (0x48ae86)
        InitWindow: if err := wb.init(widget); err != nil {
C:/G/src/github.com/lxn/walk/widget.go:94 (0x48833b)
        InitWidget: if err := InitWindow(widget, parent, className, style|win.WS
_CHILD, exStyle); err != nil {
C:/G/src/github.com/lxn/walk/listbox.go:42 (0x470837)
        NewListBox: 0)
C:/G/src/github.com/lxn/walk/declarative/listbox.go:51 (0x4bb952)
        ListBox.Create: w, err := walk.NewListBox(builder.Parent())
<autogenerated>:49 (0x4bec7d)
C:/G/src/github.com/lxn/walk/declarative/builder.go:253 (0x4b9046)
        (*Builder).InitWidget: if err := child.Create(b); err != nil {
C:/G/src/github.com/lxn/walk/declarative/splitter.go:114 (0x4bc4c0)
        VSplitter.Create: })
<autogenerated>:76 (0x4bf2cd)
C:/G/src/github.com/lxn/walk/declarative/builder.go:253 (0x4b9046)
        (*Builder).InitWidget: if err := child.Create(b); err != nil {
C:/G/src/github.com/lxn/walk/declarative/mainwindow.go:98 (0x4bc1c1)
        MainWindow.Create: })
C:/G/src/github.com/lxn/walk/declarative/mainwindow.go:108 (0x4bc2e2)
        MainWindow.Run: if err := mw.Create(); err != nil {
C:/G/src/github.com/lxn/walk/examples/listbox/listbox.go:44 (0x4013e8)
        main: }.Run()); err != nil {
c:/go/src/runtime/proc.go:63 (0x41624c)
        main: main_main()
c:/go/src/runtime/asm_386.s:2287 (0x436651)
        goexit:

**Comment by tadvi** [comment]
Make sure you have yourexename.manifest file in the same folder. Or use rsrc.exe tool to embed manifest into the binary.
Read main page of this framework. It covers manifest.

**Comment by tadvi** [comment]
Also note that walk does not work on Go 1.4.2. At least did not work for me on amd64. I had to downgrade to Go 1.3.2.

**Comment by alexbrainman** [comment]
I just tried both this examples on current go tip, and they seems to work on both 386 and amd64.

Alex

**Comment by lxn** [comment]
Thanks for checking them out.

You are right, they seem to work. But yesterday I stress tested some of my apps built with walk and when a certain amount of garbage was generated, they all crashed on Go 1.2.2, 1.3.2, 1.3.3 and 1.5 beta 1. Most of the time it got interesting around 64 - 85 MB of memory usage. The walk databinding example can also be used to showcase the crashing. Enter some data on the dialog to appease the data binder and then hold down the return key a few minutes. It just got me an interesting crash mentioning something like "stack barrier lost" on 1.5 beta.

I'm out of ideas where to look. Checked all occurrences of `uintptr(`, `SendMessage`, `Syscall` and whatnot :-(

**Comment by alexbrainman** [comment]
I will try  "databinding example" when I have some time.If you're interested maybe you can write some test similar to TestReturnAfterStackGrowInCallback from runtime package. It might give you better "stress testing".

Alex

**Comment by alexbrainman** [comment]
I tried databinding example as per your suggestion. I cannot break it either. I tried both 386 and amd64. I use: go version devel +7c767fd Sun Jul 12 18:06:34 2015 +0000 windows/amd64.

Alex

**Comment by lxn** [comment]
OK, so the mystery of the crashes I still see on top of all Go versions seems solved. There are just some resource leaks. If either 10000 user32 objects or 10000 gdi objects are reached the ship sinks.

Will continue to investigate and try to come up with a fix.

Regarding Go 1.4, I'll just call it a bad release for walk and leave it alone.

**Comment by lxn** [comment]
The resource leaks should be fixed now, closing this issue.
