### ISSUE TITLE
Add ability to have both image and text in the toolbar

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#145]
Toolbars with icons are great when you have lots of actions you want to display in the toolbar.
But when there are only 3-5 actions then buttons are way too small to hit. Also text makes for easier way to identify what button does.

Request: add ability to have both image and text in the toolbar.

This is actual walk based application in the screenshot. I had to hack to get images+text in the toolbar. It would be nice to have it as built-in feature.

![capture](https://cloud.githubusercontent.com/assets/3864876/9087477/efee56dc-3b58-11e5-92aa-1caa7e4bfcfc.PNG)

**Comment by lxn** [comment]
It's finally done :-)
