### ISSUE TITLE
TableView problem in new walk version when inside HSplitter

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#146]
I have upgraded from 1.3.1 to Go 1.5r1 and updated walk to most recent version.
Rebuild apps could no longer run. Traced the problem to mw.Run() call.
Then disabled controls inside the window Create() and traced the problem to TableView{} creation.

Once TableView{} creation is disabled then window works and mw.Run() is successful.
Standard example: github.com\lxn\walk\examples\tableview also works. 

The difference is that my TableView{} creation is inside HSplitter. 
Once I modified example github.com\lxn\walk\examples\tableview to create TableView{} inside HSplitter{} it also failed and can not display window anymore.

This is simplified example below. I know that HSplitter only has one child in this modified example. My app has many child items and still fails.

The point is that TableView{} seems to fail if placed inside HSplitter. I have number of apps structured with V and/or HSplitters. They are nice. Hope that is enough details to fix this problem.

func main() {
	rand.Seed(time.Now().UnixNano())

	model := NewFooModel()

	MainWindow{
		Title:  "Walk TableView Example",
		Size:   Size{800, 600},
		Layout: VBox{MarginsZero: true},
		Children: []Widget{
			PushButton{
				Text:      "Reset Rows",
				OnClicked: model.ResetRows,
			},
			HSplitter{
				Name: "hSplitter",
				Children: []Widget{
					TableView{
						AlternatingRowBGColor: walk.RGB(255, 255, 224),
						CheckBoxes:            true,
						ColumnsOrderable:      true,
						Columns: []TableViewColumn{
							{Title: "#"},
							{Title: "Bar"},
							{Title: "Baz", Format: "%.2f", Alignment: AlignFar},
							{Title: "Quux", Format: "2006-01-02 15:04:05", Width: 150},
						},
						Model: model,
					},
				},
			},
		},
	}.Run()
}

**Comment by lxn** [comment]
No idea what's going on here, but the modified tableview example works for me with Go 1.5 rc1 32/64 bit on Windows 7 64 bit.

**Comment by tadvi** [comment]
This is full example that fails.

Is there any way to debug this? Where should I enter print statements inside walk/win to get some idea why and where it is failing?

I am using Go 1.5r1 under Windows 8.1 and Windows 10.

```
package main

import (
	"math/rand"
	"sort"
	"strings"
	"time"
)

import (
	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

type Foo struct {
	Index   int
	Bar     string
	Baz     float64
	Quux    time.Time
	checked bool
}

type FooModel struct {
	walk.TableModelBase
	walk.SorterBase
	sortColumn int
	sortOrder  walk.SortOrder
	evenBitmap *walk.Bitmap
	oddIcon    *walk.Icon
	items      []*Foo
}

func NewFooModel() *FooModel {
	m := new(FooModel)
	m.evenBitmap, _ = walk.NewBitmapFromFile("../img/open.png")
	m.oddIcon, _ = walk.NewIconFromFile("../img/x.ico")
	m.ResetRows()
	return m
}

// Called by the TableView from SetModel and every time the model publishes a
// RowsReset event.
func (m *FooModel) RowCount() int {
	return len(m.items)
}

// Called by the TableView when it needs the text to display for a given cell.
func (m *FooModel) Value(row, col int) interface{} {
	item := m.items[row]

	switch col {
	case 0:
		return item.Index

	case 1:
		return item.Bar

	case 2:
		return item.Baz

	case 3:
		return item.Quux
	}

	panic("unexpected col")
}

// Called by the TableView to retrieve if a given row is checked.
func (m *FooModel) Checked(row int) bool {
	return m.items[row].checked
}

// Called by the TableView when the user toggled the check box of a given row.
func (m *FooModel) SetChecked(row int, checked bool) error {
	m.items[row].checked = checked

	return nil
}

// Called by the TableView to sort the model.
func (m *FooModel) Sort(col int, order walk.SortOrder) error {
	m.sortColumn, m.sortOrder = col, order

	sort.Stable(m)

	return m.SorterBase.Sort(col, order)
}

func (m *FooModel) Len() int {
	return len(m.items)
}

func (m *FooModel) Less(i, j int) bool {
	a, b := m.items[i], m.items[j]

	c := func(ls bool) bool {
		if m.sortOrder == walk.SortAscending {
			return ls
		}

		return !ls
	}

	switch m.sortColumn {
	case 0:
		return c(a.Index < b.Index)

	case 1:
		return c(a.Bar < b.Bar)

	case 2:
		return c(a.Baz < b.Baz)

	case 3:
		return c(a.Quux.Before(b.Quux))
	}

	panic("unreachable")
}

func (m *FooModel) Swap(i, j int) {
	m.items[i], m.items[j] = m.items[j], m.items[i]
}

// Called by the TableView to retrieve an item image.
func (m *FooModel) Image(row int) interface{} {
	if m.items[row].Index%2 == 0 {
		return m.evenBitmap
	}

	return m.oddIcon
}

func (m *FooModel) ResetRows() {
	// Create some random data.
	m.items = make([]*Foo, rand.Intn(50000))

	now := time.Now()

	for i := range m.items {
		m.items[i] = &Foo{
			Index: i,
			Bar:   strings.Repeat("*", rand.Intn(5)+1),
			Baz:   rand.Float64() * 1000,
			Quux:  time.Unix(rand.Int63n(now.Unix()), 0),
		}
	}

	// Notify TableView and other interested parties about the reset.
	m.PublishRowsReset()

	m.Sort(m.sortColumn, m.sortOrder)
}

func main() {
	rand.Seed(time.Now().UnixNano())

	model := NewFooModel()

	MainWindow{
		Title:  "Walk TableView Example",
		Size:   Size{800, 600},
		Layout: VBox{MarginsZero: true},
		Children: []Widget{
			PushButton{
				Text:      "Reset Rows",
				OnClicked: model.ResetRows,
			},
			HSplitter{
				Name: "hSplitter",
				Children: []Widget{
					PushButton{
						Text:      "Do nothing",
					},
					TableView{
						AlternatingRowBGColor: walk.RGB(255, 255, 224),
						CheckBoxes:            true,
						ColumnsOrderable:      true,
						Columns: []TableViewColumn{
							{Title: "#"},
							{Title: "Bar"},
							{Title: "Baz", Format: "%.2f", Alignment: AlignFar},
							{Title: "Quux", Format: "2006-01-02 15:04:05", Width: 150},
						},
						Model: model,
					},
				},
			},
		},
	}.Run()
}

```

**Comment by tadvi** [comment]
The problem might be that I am using newer versions of Windows while you use Windows 7.

**Comment by lxn** [comment]
On Windows 8 I have been able to reproduce the problem. Please try the latest version.

**Comment by tadvi** [comment]
Looks like this fixed it.
