### ISSUE TITLE
Problem with font in groupbox

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#147]
Once upgraded to Go 1.5r1 and newest walk version I find some fonts of being incorrect size. 
There is one example where radio button groupbox font is off: 

![capture](https://cloud.githubusercontent.com/assets/3864876/9174809/3a63faaa-3f50-11e5-91cb-0150c80a1067.PNG)

**Comment by tadvi** [comment]
Maybe it is just Windows 10 issue.

**Comment by lxn** [comment]
It was a bug, please try latest changes.

**Comment by tadvi** [comment]
Confirming that it is fixed. 
By the way thanks for the new Toolbar features. Ability to have icons in the toolbar is very useful.

**Comment by lxn** [comment]
You're welcome :-)

Most stuff you have asked for, I need myself also.

**Comment by tadvi** [comment]
Two items that are missing for me are:

1. Diagram component. Ability to create diagrams with blocks (rectangular or rounded shapes).
2. PropertyGrid. Basically a TableView where you can edit values with in-place edit box that appears when you click on a field in TableView. PropertyGrid is featured in .NET that's where I have used it. But I think Qt and wxWidgets has it too.

But both of these I imagine are "big ticket" items. So I do not have my hopes high...

Anyhow,  :+1:
