### ISSUE TITLE
Ordering of table columns in TableView when loaded from Settings.

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#148]
Initially when application starts (no walk.NewIniFileSettings) columns in TableView are in the right order. 

When application saves columns on exit and gets restarted, columns are loaded in the reverse order.
Peeking into "settings.ini" for the application appears that column names are not even being stored.

This was not the case with prior versions of 'walk'. Columns for TableView would never be reversed.

**Comment by tadvi** [comment]
This is just to show what I meant.

![capture](https://cloud.githubusercontent.com/assets/3864876/9198746/3735afc4-400c-11e5-877c-8b06f04bfb3b.PNG)

**Comment by lxn** [comment]
To fix this, you need to give every column a name. Please have a look at the settings example.

**Comment by tadvi** [comment]
Thank you.
It works with "Name" set.
