### ISSUE TITLE
Run examples error .

### ISSUE THREAD

**Issue by ablegao** [lxn/walk#150]
go build 
imageviewer.exe

Go version: golang 1.4.2

System version : Windows Xp 32bit

panic: The specified procedure could not be found.

goroutine 1 [running]:
github.com/lxn/win.MustGetProcAddress(0x77d10000, 0x5fcee8, 0x1a, 0x11)
	C:/mygo/src/github.com/lxn/win/win.go:55 +0x6e
github.com/lxn/win.init·12()
	C:/mygo/src/github.com/lxn/win/user32.go:1604 +0x57
github.com/lxn/win.init()
	C:/mygo/src/github.com/lxn/win/winspool.go:98 +0x80
github.com/lxn/walk.init()
	C:/mygo/src/github.com/lxn/walk/window.go:1436 +0x95
github.com/lxn/walk/declarative.init()
	C:/mygo/src/github.com/lxn/walk/declarative/webview.go:59 +0x59
main.init()
	C:/mygo/src/github.com/lxn/walk/examples/imageviewer/imageviewer.go:153 +0x3f

goroutine 2 [runnable]:
runtime.forcegchelper()
	c:/go/src/runtime/proc.go:90
runtime.goexit()
	c:/go/src/runtime/asm_386.s:2287 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	c:/go/src/runtime/mgc0.go:82
runtime.goexit()
	c:/go/src/runtime/asm_386.s:2287 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	c:/go/src/runtime/malloc.go:712
runtime.goexit()
	c:/go/src/runtime/asm_386.s:2287 +0x1

**Comment by lxn** [comment]
Walk doesn't work with Go 1.4.x, sorry. Please use another Go version.
