### ISSUE TITLE
Example notifyicon/notifyicon.go no longer works under Windows 10

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#152]
I am guessing Windows 10 changed how notifications work in Windows.
Therefore most of code in example/notifyicon/notifyicon.go no longer produces notifications such as balloon tooltips or similar.

Following calls worked fine on Windows 8.1 but I do not see any notifications under Windows 10:

```
if err := ni.ShowCustom("Website Down ", "www.xrrr.com"); err != nil {
	log.Fatalln(err)
}

if err := ni.ShowInfo("Walk NotifyIcon Example", "Click the icon to show again."); err != nil {
	log.Fatal(err)
}

if err := ni.SetToolTip("Click for info or use the context menu to exit."); err != nil {
	log.Fatal(err)
}
```

In general Windows 10 does have notifications that popup from the right lower corner of the screen. There is also 'notification area' that opens up on the right hard side of the screen.

**Comment by proullon** [comment]
I confirm, not working on windows 10

**Comment by lxn** [comment]
This somehow seems to work now.
