### ISSUE TITLE
Make visible some of the functions from Canvas inside 'walk'

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#154]
I found myself in need to create something that could be called CustomCanvas component. Which is a mix of MyWidget from externalwidgets.go example and CustomWidget used in drawing.go. 
CustomCanvas would basically be a custom widget with basic drawing capabilities plus it would accept and react to mouse and key press events.

Main problem is that number of useful Canvas funcs are not exported:
```
func newCanvasFromHWND(hwnd win.HWND) (*Canvas, error)
func newCanvasFromHDC(hdc win.HDC) (*Canvas, error)
```

They are not reachable outside of 'walk'. So if I try to create my own handle, it does not compile:
```
case win.WM_PAINT:
  // I need to do: canvas, err := newCanvasFromHDC(hdc) in order to create and pass Canvas into paintFunc
```

Also cw.hWnd for the current widget is not exported and example uses it. But WndProc(hwnd win.HWND..) also gets 'hwnd', so I am not sure if I can use it.

Maybe there is some other way how to implement CustomCanvas: which is in essence just CustomWidget with paintFunc + some mouse/key event handling.

**Comment by tadvi** [comment]
Another alternative for me would be to take customwidget.go, copy&rename it into customcanvas.go, add event handling for mouse & keys and have it in 'walk' as part of the available controls. 

Then these would not need to be exported. 
```
func newCanvasFromHWND(hwnd win.HWND) (*Canvas, error)
func newCanvasFromHDC(hdc win.HDC) (*Canvas, error)
```

And if 'walk' users find a need to have CustomCanvas they could just use it instead of reinventing the wheel.

**Comment by lxn** [comment]
What events do you need that `CustomWidget` does not provide?

Maybe the `CreateCanvas` method on `Window` could also be useful to you.

**Comment by lxn** [comment]
Oh, there is also the `Handle` method on `Window` which gives you the `HWND`.

**Comment by tadvi** [comment]
I do not know how to attach mouse and keyboard events to ```CustomWidget```. Maybe you could just alter ```drawing.go``` example so it would show how to handle mouse and keyboard events when working with ```CustomWidget```.
```drawing.go``` example shows how to handle painting. Which is great.

**Comment by lxn** [comment]
Keyboard and mouse events are supported on all widgets, also on [CustomWidget](https://github.com/lxn/walk/blob/master/declarative/customwidget.go#L27).

**Comment by tadvi** [comment]
Great. Next time I will spend more time going thru the code before I post here. Thank you.
