### ISSUE TITLE
CustomWidget drawing and flicker

### ISSUE THREAD

**Issue by tadvi** [lxn/walk#155]
I am implementing ```CustomWidget``` and drawing number of items on it. It is a diagram with blocks.
All works well. Only problem is that sometimes items in ```CustomWidget``` have to be updated because blocks are being moved around by mouse or blocks get deleted.

My poor implementation simply calls Invalidate() on the ```CustomWidget```, and all blocks get repainted.
It is work in progress. 

Now I am in cross roads: problem is that Invalidate() causes flicker. 

1. I could try to minimize flicker by trying to repaint only parts that have been updated. But it is complex and involves a lot of house-keeping. Also sometimes many blocks get updated so that would still result in flicker.

2. I could try to first draw on Bitmap and then quickly switch into new canvas when drawing is over.

3. Maybe there are other ways to do it?

Any advice would be appreciated. If I get this to work reasonably well I would like to contribute this as another sample in walk/examples.

**Comment by lxn** [comment]
Haven't used the drawing stuff myself, besides the drawing example, so it's difficult to give advice.

Probably there should be some double buffering support in `CustomWidget`, as well as more precise invalidation like an `InvalidateRectangle` method.

I would suggest to try the latter one first, seems easier to implement. Probably won't be able to add this myself before Monday though, but maybe you want to give it a try?

**Comment by tadvi** [comment]
```InvalidateRectangle``` I am not sure how would this work in this case. Blocks can overlay one another. 

I have wxWidgets based C++ diagramming framework that I use now for few projects. Old code. That framework seems to be doing double buffering. My initial idea was to migrate this C/C++ code into Go + walk combo.
