### ISSUE TITLE
Initial position of the windows?

### ISSUE THREAD

**Issue by superuser123** [lxn/walk#157]
I just have developed a go application by using walk.
The problem is that the initial position of windows are at random.
Is there a way to set the initial position of windows?
And can I add "minimized button" and "maximized button"?

**Comment by lxn** [comment]
To set the initial position you could try the `SetBounds` method before the window is made visible. You may also be interested in the integrated settings system. See the settings example.

You always get minimize/restore/maximize buttons with `MainWindow` and none of them with `Dialog`. There is no support for changing those once a window has been created, but it may be useful to provide more "constructor" variants if there is enough demand.

**Comment by superuser123** [comment]
It was very kind of you. Thank you.

**Comment by superuser123** [comment]
One more question.
I had set the icon of the exe file. But after I set the icon of the windows(of my program), the icon of the exe file disappeared. Could you explain about this and recommend a way to solve this problem?
Thanks.

**Comment by lxn** [comment]
No idea what may have happened there.

What works for me is using the [rsrc](https://github.com/akavel/rsrc) tool to embed an icon into the executable and call `walk.NewIconFromResourceId` to load it for usage as main window icon.

If you do the same, maybe you have to regenerate the `rsrc.syso` file.

**Comment by tadvi** [comment]
I have release.bat file that does build and regenerates resource file for the binary.
release.bat gets executed just before product update, and goes something like this:

set GOOS=windows
set GOARCH=386
rsrc -manifest app.manifest -ico app.ico -o rsrc.syso
go build -ldflags="-H windowsgui"

REM I hope this helps.

**Comment by superuser123** [comment]
Thanks.
