### ISSUE TITLE
MouseEvent sent to another WindowBase instance

### ISSUE THREAD

**Issue by proullon** [lxn/walk#160]
Hi,

I have written a simple program where I create a walk.MainWindow and attach a handler to KeyDown() and MouseMove().

My KeyDown handler is called when I press a key but my MouseMove handler is never called when I move the mouse.
I added some debug logs in lxn/walk/window.go L{1373, 1415}, I saw that publishMouseEvent is called when I move the mouse.
I started printing the value of the WindowBase pointer, and I have a different value when logs is printed for MouveMove or KeyDown.

So, when the WndProc() calls publishMouseEvent(), itself calling publisher.Publish(),  the MouseEvent.handlers slice is empty because it is not the same object I called Attach() upon.

Hence, my handler is never called because he is attached to another WindowBase instance.

I couldn't figure out in the code why this is happening, so here I am.

OS: Windows 10
Go: 1.5.1

**Comment by lxn** [comment]
Thanks for reporting!

Please try again with the latest changes to walk.

**Comment by proullon** [comment]
Nice ! Testing tonight :)

**Comment by proullon** [comment]
It's working thanks :)
