### ISSUE TITLE
Clear GroupBox background

### ISSUE THREAD

**Issue by rodolfoag** [lxn/walk#161]
Hi Alexander, great lib!

Is it possible to clear the GroupBox background (or set color) using the declarative form?

Thx,

**Comment by lxn** [comment]
Hi Rodolfo, thanks for the kind words!

I'm afraid it's currently not even possible using the imperative apis. I'll have to investigate this a bit and hope to come up with some improvement soonish.

**Comment by rodolfoag** [comment]
Ok Alexandre, thank you for your quick reply.
