### ISSUE TITLE
Walk to support window maximize, minimize, and are prohibited to modify size?

### ISSUE THREAD

**Issue by CodyGuo** [lxn/walk#163]
Walk to support window maximize, minimize, and are prohibited to modify size?If not whether can support?I by modifying the source code to support these three functions, but don't want to go to modify the source code every time?Can you add these three functions to walk?Because I write the code is not good enough, so there is no post, I believe that you write will be better than me.

**Comment by lxn** [comment]
There is support for [fixed size dialogs](https://github.com/lxn/walk/commit/355b16e987b2440da935d8f1cb6a324b7adb5569).

Do you need fixed size on `MainWindow`?

**Comment by CodyGuo** [comment]
Yes, and ban to maximize and minimize, it is best to all of these can be set.There is a setup screen center would be even better.
