### ISSUE TITLE
For help, how to add menus and toolbars to the Dialog?

### ISSUE THREAD

**Issue by CodyGuo** [lxn/walk#164]
I use below way to add menu bar, and when the toolbar has been can't do it like mainwindows to add menu bar and toolbar.Can you provide an example?
// 工具菜单
    mw.ui.ToolsMu, _ = walk.NewMenu()

    mw.ui.SettingAction = walk.NewAction()
    mw.ui.SettingAction.SetText("设置")

    mw.ui.SetToolBar, _ = walk.NewToolBar(mw)
    mw.ui.SetToolBar.Actions().AddMenu(mw.ui.ToolsMu)
    mw.ui.SetToolBar.Actions().Add(mw.ui.SettingAction)

**Comment by lxn** [comment]
Menus on Dialogs are not supported, sorry.

**Comment by CodyGuo** [comment]
Ok, thank you.
