### ISSUE TITLE
How can i auto refresh taleview date ?

### ISSUE THREAD

**Issue by buyapeng** [lxn/walk#165]
i add a tableview in MainWindow and i want auto refresh date ?

**Comment by lxn** [comment]
Not sure I understand the question correctly.

If you want to make a `TableView` pick up a change to a single row, call the `PublishRowChanged` method of your model, if it embeds `walk.TableModelBase`, or raise the `RowChanged` event of your own implementation of `walk.TableModel`. If more than one row has changed, you might have to use `PublishRowsReset` / `RowsReset` instead.

**Comment by buyapeng** [comment]
i read you examples tableview ,Refresh date is use 	

		PushButton{
				Text:      "Reset Rows",
				OnClicked: model.ResetRows,
				//OnClicked: model.ResetRows,

but i want  TableView auto Refresh Data  Perform once every 5 minutes，No Click Button。

**Comment by buyapeng** [comment]
I want using   for  at OnClicked  
OnClicked: func() {
					for i := 0; i < 5; i++ {
						time.Sleep(3 * time.Second)
						event1.ResetRows()
					}


but  Each time the data is refreshed after the For cycle is complete。

**Comment by lxn** [comment]
You will probably need to run a for loop on a different goroutine and have a `time.Ticker` periodically trigger a call to `event1.ResetRows`, wrapped by `Window.Synchronize`, so it is done from the UI thread.

Somewhat like this:

```go
go func() {
	ticker := time.NewTicker(time.Second * 3)

	for {
		select {
		case <-ticker.C:
			mw.Synchronize(func() {
				event1.ResetRows()
			})
		}
	}
}()
```

**Comment by buyapeng** [comment]
It's OK  Thks
