### ISSUE TITLE
Take a screenshot from a window

### ISSUE THREAD

**Issue by ktye** [lxn/walk#190]
I want to implement the ability to take a screenshot from a window or a dialog from within walk.
The result should be an image.RGBA.

I do have a working prototype that uses the WM_PRINT message to create a win.HBITMAP from a walk.Window. I think we have to use WM_PRINT and not the bitmap directly, because only this ensures it is always painted.

When this is working we could auto-generate screenshots for all widgets for documentation purpose.

Would you accept the addition?
I propose the following api:

```go
func (wb *WindowBase) Image() (image.Image, error)
```

**Comment by lxn** [comment]
Sounds good!
