### ISSUE TITLE
Error when get walk

### ISSUE THREAD

**Issue by z954134** [lxn/walk#200]
when i go get github.com/lxn/walk

E:\GOPATH\src\github.com\lxn\walk\bitmap.go:120: undefined: win.PRF_CHILDREN
E:\GOPATH\src\github.com\lxn\walk\bitmap.go:120: undefined: win.PRF_CLIENT
E:\GOPATH\src\github.com\lxn\walk\bitmap.go:120: undefined: win.PRF_ERASEBKGND
E:\GOPATH\src\github.com\lxn\walk\bitmap.go:120: undefined: win.PRF_NONCLIENT
E:\GOPATH\src\github.com\lxn\walk\bitmap.go:120: undefined: win.PRF_OWNED
E:\GOPATH\src\github.com\lxn\walk\canvas.go:266: undefined: win.Polyline
E:\GOPATH\src\github.com\lxn\walk\window.go:1107: undefined: win.GetDIBits
E:\GOPATH\src\github.com\lxn\walk\window.go:1113: undefined: win.GetDIBits

**Comment by lxn** [comment]
Please update your copy of github/lxn/win.
