### ISSUE TITLE
Label the mouse events trigger?

### ISSUE THREAD

**Issue by CodyGuo** [lxn/walk#220]
OnMouseUp: func(x, y int, button walk.MouseButton) {
                    log.Println("up", x, y, button)
        },

**Comment by lxn** [comment]
Sorry for the late reply. Could you please clarify what you are asking for?

**Comment by CodyGuo** [comment]
I'm sorry, my English is a little bad。
Label the OnMouseUp can't see the desired effect，

**Comment by CodyGuo** [comment]
Label MouseEvent No effect。



    mw.label.MouseDown().Attach(func(x, y int, button walk.MouseButton) {
		log.Println(x, y, button)
	})

	mw.label.MouseWheel().Attach(func(x, y int, button walk.MouseButton) {
		log.Println(x, y, button)
	})

	mw.label.MouseMove().Attach(func(x, y int, button walk.MouseButton) {
		log.Println(x, y, button)
	})

	mw.label.MouseUp().Attach(func(x, y int, button walk.MouseButton) {
		log.Println(x, y, button)
	})
