### ISSUE TITLE
using walk examples without "dot import" 

### ISSUE THREAD

**Issue by mewalig** [lxn/walk#221]
Many of the walk examples (such as 
https://github.com/lxn/walk/blob/df9367a7d4e5ccc567a4014f42de6d22a082c895/examples/webview/webview.go) use the "dot import" syntax. This is a syntax that is discouraged (e.g. see https://golang.org/doc/go1compat and "We do not recommend the use of import . outside of tests, and using it may cause a program to fail to compile in future releases").

I've tried unsuccessfully to modify the example code to run without the dot import. Could anyone please tell me where this is going wrong:

with dot import (a la example code):
```
import (
	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

func main() {
	var le *walk.LineEdit
	var wv *walk.WebView

	MainWindow{
		Title:   "Walk WebView Example",
	
```

failed attempt:
```
import (
	"github.com/lxn/walk"
	"github.com/lxn/walk/declarative"
)

func main() {
	var le *walk.LineEdit
	var wv *walk.WebView

	walk.MainWindow{
		walk.Title:   "Walk WebView Example", ...
	
```

**Comment by lxn** [comment]
This should work (not tested):

```Go
package main

import (
	"github.com/lxn/walk"
	"github.com/lxn/walk/declarative"
)

func main() {
	var le *walk.LineEdit
	var wv *walk.WebView

	declarative.MainWindow{
		Title:   "Walk WebView Example",
		MinSize: declarative.Size{800, 600},
		Layout:  declarative.VBox{MarginsZero: true},
		Children: []declarative.Widget{
			declarative.LineEdit{
				AssignTo: &le,
				Text:     declarative.Bind("wv.URL"),
				OnKeyDown: func(key walk.Key) {
					if key == walk.KeyReturn {
						wv.SetURL(le.Text())
					}
				},
			},
			declarative.WebView{
				AssignTo: &wv,
				Name:     "wv",
				URL:      "http://golang.org",
			},
		},
	}.Run()
}
```

**Comment by tajtiattila** [comment]
Although the word "declarative" is fine for the package name, I find it too long for normal use (hard to write and read). I would just import it as "decl" or even just "d" using named imports to have shorter code for readability and to avoid conflicts in the future.

`import decl "github.com/lxn/walk/declarative"`

**Comment by mewalig** [comment]
thank you both!
