### ISSUE TITLE
Webview example can NOT be launched in Win10 64

### ISSUE THREAD

**Issue by ZhuBicen** [lxn/walk#226]
panic: interface conversion: *walk.property is not walk.Condition: missing method Satisfied

goroutine 1 [running, locked to thread]:
panic(0x584a40, 0xc042040b40)
	C:/Go/src/runtime/panic.go:500 +0x1af
github.com/lxn/walk/declarative.(*Builder).conditionOrProperty.func1(0x5bce50, 0x6, 0x5bc400, 0x2, 0xc0420432f0)
	D:/opt/gopath/src/github.com/lxn/walk/declarative/builder.go:466 +0x117
github.com/lxn/walk/declarative.(*Builder).conditionOrProperty(0xc04208e100, 0x58d2a0, 0xc04203fe20, 0x58d2a0, 0xc04203fe20)
	D:/opt/gopath/src/github.com/lxn/walk/declarative/builder.go:507 +0x4c1
github.com/lxn/walk/declarative.(*Builder).initProperties(0xc04208e100, 0x0, 0x0)
	D:/opt/gopath/src/github.com/lxn/walk/declarative/builder.go:403 +0x88d
github.com/lxn/walk/declarative.(*Builder).InitWidget(0xc04208e100, 0x6b21a0, 0xc04208c6c0, 0x6b6bc0, 0xc042092000, 0xc042031140, 0x0, 0x0)
	D:/opt/gopath/src/github.com/lxn/walk/declarative/builder.go:339 +0x944
github.com/lxn/walk/declarative.MainWindow.Create(0xc042066080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	D:/opt/gopath/src/github.com/lxn/walk/declarative/mainwindow.go:124 +0x501
github.com/lxn/walk/declarative.MainWindow.Run(0xc042066080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	D:/opt/gopath/src/github.com/lxn/walk/declarative/mainwindow.go:134 +0x89
main.main()
	D:/7_years/walk/examples/webview/webview.go:36 +0x3c2

**Comment by lxn** [comment]
That's a [known problem](https://github.com/lxn/walk/issues/10). I have wasted many hours over the past years trying to fix it. IIRC it seemed to me like some incompatibility between 64 bit MinGW and internal exception handling in the web browser control. I have no plans to investigate further, sorry.
