### ISSUE TITLE
Using custom icons with MainWindow?

### ISSUE THREAD

**Issue by tmm1** [lxn/walk#236]
Apps appear to use the default system icon here: https://github.com/lxn/walk/blob/c5fab5f5b34c1412cef1a8513ea10e1a7a71a7a9/window.go#L334

Is it possible to specify a custom icon? I am already embedding one with rsrc/goversioninfo but its not being used.

**Comment by tmm1** [comment]
Never mind, I misunderstood what `IDI_APPLICATION` means. Seems like this might be an issue with goversioninfo.

**Comment by tmm1** [comment]
The SetIcon method on MainWindow lets you do this.

**Comment by tmm1** [comment]
I'm still having a hard time figuring this out.

In https://github.com/lxn/walk/issues/157#issuecomment-140075378, it says:

>What works for me is using the rsrc tool to embed an icon into the executable and call walk.NewIconFromResourceId to load it for usage as main window icon.

How do you find the correct resource id to load the icon?

**Comment by lxn** [comment]
There is an old issue on the [rsrc](https://github.com/akavel/rsrc) repo, please read the text below the code block:
https://github.com/akavel/rsrc/issues/5#issuecomment-38121327

**Comment by tmm1** [comment]
Thanks. Looks like the ID is printed out when using `rsrc` now (but not by `goversioninfo`, but that uses the same code and IDs). You can also use `pedump -R` to list out the resources for an exe and find the ID that way.

Also remember to create the MainWindow before calling SetIcon on it. Something like:

```
MainWindow{
  AssignTo: &mainWindow,
}.Create()
mainWindow.SetIcon(icon)
mainWindow.Run()
```

**Comment by cyclamenkde** [comment]
package main

import (
	"log"
	"strings"

	walk "github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

func main() {
	var inTE, outTE *walk.TextEdit
	var mw *walk.MainWindow

	icon, _ := walk.NewIconFromFile("favicon.ico")

	if _, err := (MainWindow{
		AssignTo: &mw,
		Title:    "SCREAMO",
		MinSize:  Size{600, 400},
		Icon:     icon,
		Layout:   VBox{},
		Children: []Widget{
			HSplitter{
				Children: []Widget{
					TextEdit{AssignTo: &inTE},
					TextEdit{AssignTo: &outTE, ReadOnly: true},
				},
			},
			PushButton{
				Text: "SCREAM",
				OnClicked: func() {
					outTE.SetText(strings.ToUpper(inTE.Text()))
				},
			},
			PushButton{
				Text: "Click",
				OnClicked: func() {
					walk.MsgBox(mw, "hello", inTE.Text(), walk.MsgBoxIconInformation)
				},
			},
		},
	}.Run()); err != nil {
		log.Fatal(err)
	}
}
