### ISSUE TITLE
OS X: package github.com/lxn/walk: no buildable Go source files

### ISSUE THREAD

**Issue by bchbchbch** [lxn/walk#240]

**Comment by cocotyty** [comment]
Just for windows only

**Comment by dwall80** [comment]
I'm hitting this as well, I work from a linux machine need to create a GUI for windows, this doesn't actually stop cross-compilation so I can cross-compile the demos and run on win VM. 
Unfortunately, it is making it impossible for me to develop with right now as it's bugging out my IDE - I'm using atom with goplus) set to run gotest and golint in on save, and it's throwing the error:

`/gopath/src/github.com/lxn/walk/tooltiperrorpresenter.go:4:2: no buildable Go source files `

would be nice to get this sorted if possible

**Comment by mewalig** [comment]
same problem
