### ISSUE TITLE
How to use "Events" (ex. Creating a digital clock)

### ISSUE THREAD

**Issue by LARGEGALAXY** [lxn/walk#245]
I have read the source code specifically for _'events.go'_; but I am unable to piece together how to create a working prototype. Let's imagine I want to create a digital clock (or _anything_ dynamic for that matter) that must tick every second (this is the event) and then updates the _Label Text_ in _MainWindow_ with the new time.

How should I go about doing this?

As I said I have read the source code, I see there is an _Event_ struct, a _Publisher_ struct, and various methods. but my lack of event-driven programming has me at a loss. Any help or examples would be fantastic.

**Comment by lxn** [comment]
You could try something like this:

```Go
package main

import (
	"time"

	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

func main() {
	var l *walk.Label

	go func() {
		ticker := time.NewTicker(time.Second)

		for {
			select {
			case <-ticker.C:
				l.Synchronize(func() {
					l.SetText(time.Now().Format("15:04:05"))
				})
			}
		}
	}()

	MainWindow{
		Title:   "Clock Example",
		MinSize: Size{300, 200},
		Layout:  VBox{},
		Children: []Widget{
			Label{
				AssignTo: &l,
				Font:     Font{Family: "Segoe UI", PointSize: 40},
			},
		},
	}.Run()
}
```

**Comment by LARGEGALAXY** [comment]
Splendid.

Thanks.
