### ISSUE TITLE
Search for TreeItem in TreeView

### ISSUE THREAD

**Issue by aboinameddave** [lxn/walk#255]
Is it possible to search for a certain TreeItem in a TreeView model?

Like in the filebrowser example, I want to search for a certain folder in the populated treeModel and set the Item as the currently selected item.

In the filebrowser example, the treeModel gets populated with:
```go
treeModel, err := NewDirectoryTreeModel()
```

Now I want to iterate through all TreeItems and select the wanted TreeItem with:
```go
treeView.SetCurrentItem(wantedItem)
```

Is there a way to do that?

**Comment by lxn** [comment]
I use the `DirectoryTreeModel` from the filebrowser example in one of my apps. One of the extensions I added there is this:
```Go
func (m *DirectoryTreeModel) FindPath(path string) *Directory {
	return m.findPathRecursive(path, m.roots)
}

func (m *DirectoryTreeModel) findPathRecursive(path string, dirs []*Directory) *Directory {
	for _, dir := range dirs {
		curPath := dir.Path()

		if strings.HasPrefix(path, curPath) {
			if curPath == path {
				return dir
			}

			if len(dir.children) == 0 {
				dir.ResetChildren()

				if len(dir.children) > 0 {
					m.PublishItemsReset(dir)
				}
			}

			if dir = m.findPathRecursive(path, dir.children); dir != nil {
				return dir
			}
		}
	}

	return nil
}
```
Then you can use it like this:
```Go
treeView.SetCurrentItem(treeModel.FindPath(somePath))
```
HTH

**Comment by aboinameddave** [comment]
Works excellent! Thank you!
