### ISSUE TITLE
Format in TableViewColumn does not work

### ISSUE THREAD

**Issue by aboinameddave** [lxn/walk#260]
In your given tableview example, when I change 

```go
Columns: []TableViewColumn{
        {Title: "#"},
	{Title: "Bar"},
	{Title: "Baz", Alignment: AlignFar},
	{Title: "Quux", Format: "2006-01-02 15:04:05", Width: 150},
},
```
to
```go
Columns: []TableViewColumn{
        {Title: "#"},
	{Title: "Bar"},
	{Title: "Baz", Format: "%.4f", Alignment: AlignFar},
	{Title: "Quux", Format: "2006-01-02 15:04:05", Width: 150},
},
```
I would expect that the output in the Baz column has 4 decimal places after the point, but it stays as if format is "%.2f"

Am I missing something or can't be format used like that to ouput a datamember?

**Comment by lxn** [comment]
Formatting `float32`, `float64` and `*big.Rat` uses `Precision` instead of `Format` to be able to get localized output.

**Comment by aboinameddave** [comment]
Thank you!

Changing to:
```go
Columns: []TableViewColumn{
        {Title: "#"},
	{Title: "Bar"},
	{Title: "Baz", Precision: 4, Alignment: AlignFar},
	{Title: "Quux", Format: "2006-01-02 15:04:05", Width: 150},
},
```

worked perfectly.
