### ISSUE TITLE
tableview is sort auto how can I remove this?

### ISSUE THREAD

**Issue by beiqing520** [lxn/walk#272]
tableview is sort auto how can I remove this?

**Comment by lxn** [comment]
Make sure your model does not implement the `Sorter` interface.

```Go
// Do this:
type MyAbcModel struct {
    ReflectTableModelBase
    // More stuff ...
}
// instead of this:
type MyAbcModel struct {
    SortedReflectTableModelBase
    // More stuff ...
}

// And this:
type MyXyzModel struct {
    TableModelBase
    // More stuff ...
}
// instead of this:
type MyXyzModel struct {
    TableModelBase
    SorterBase
    // More stuff ...
}
```

**Comment by beiqing520** [comment]
but when user click the column I need sort , if I do like this it can not sort  and I have read your code:
func (tv *TableView) UpdateItem(index int) error {
	if s, ok := tv.model.(Sorter); ok {
		if err := s.Sort(s.SortedColumn(), s.SortOrder()); err != nil {
			return err
		}

		return tv.Invalidate()
	} else {
		if win.FALSE == tv.SendMessage(win.LVM_UPDATE, uintptr(index), 0) {
			return newError("LVM_UPDATE")
		}
	}

	return nil
}
why when UpdateItem auto sort
