### ISSUE TITLE
how can I create a children window

### ISSUE THREAD

**Issue by 380wmda999** [lxn/walk#273]
I use MainWindow after call MainWindow.Create()  I called win.SetParent but It have a Flashing, how can I  SetParent before Create

**Comment by lxn** [comment]
I'm afraid I don't understand your question. Do you mean the `SetParent` function from the `win` package or is `win` some `walk.Window`?

It would help if you could provide some code to demostrate the problem.

**Comment by 380wmda999** [comment]
I want to use walk.MainWindow to create a child window and when close the child window close I need call back how can I do

**Comment by lxn** [comment]
It sounds to me like you want a `Dialog`.

Please see the databinding example for how they are used.
