### ISSUE TITLE
text edit have a "rtl" style?

### ISSUE THREAD

**Issue by saturn99** [lxn/walk#274]
hello

how to i can create "rtl" style for "text edit" ? 
the "walk" support this features?

**Comment by lxn** [comment]
Hi!

I'm not sure what is required to make this work. If just adding `WS_EX_RTLREADING` to all widgets is sufficient, then it can be supported soon. But I guess it would be nice if layouts supported mirroring depending on the reading order, which would be a bit more involved to implement.

**Comment by rafirouzi** [comment]
rtl usable for multi language typing.
better, add to default features

**Comment by lxn** [comment]
I have just pushed a first attempt for rtl and alignment support.

Sadly `RightToLeftLayout` and `Alignment` don't play nice together, so I probably will have to make breaking changes. Anyway, please try this stuff and let me know your thoughts.

**Comment by rafirouzi** [comment]
In winform,alignment used only for few element, like textedit,label,... 
But dont use other
And rtl used only for few element...

**Comment by woozhu** [comment]
I guess that they are different things ，like a box in every widget ，in the box the text is rtl，and the box is aligment. so every text is wrppered by box.
