### ISSUE TITLE
walk.Image from byte array

### ISSUE THREAD

**Issue by JamieSinn** [lxn/walk#281]
Is this possible?
I've got some embedded images using go-bindata, and I wanted to use the byte array that it returns as the image.

**Comment by lxn** [comment]
Should be possible. Please have a look at the imageicon example.

**Comment by JamieSinn** [comment]
I ended up using image/jpeg and getting the image that way. Much easier.

**Comment by JamieSinn** [comment]
Currently having issues converting an image.Image to a walk.Image for an ImageView.

I'm trying to display an image in the GUI and it's proving to be more difficult than I anticipated.

I checked out the imageicon, as well as the imageviewer, but neither seem to give a definitive answer.

**Comment by lxn** [comment]
Just to be sure, have you tried to convert an `image.Image` using `walk.NewBitmapFromImage` and it would not work, or by some other means?

**Comment by JamieSinn** [comment]
Here's the relevant snippets:

```
om5p, err := resources.Asset("om5p.png")

	if err != nil {
		return 0, errors.New("Failed to load OM5P Image from resources.")
		fmt.Println("Failed to load OM5P Image from resources.1")
	}

	jpegdata, err := jpeg.Decode(bytes.NewReader(om5p))

	om5pImg, err := walk.NewBitmapFromImage(jpegdata)

	if err != nil {
		fmt.Println("Failed to load OM5P Image from resources.2")
		return 0, errors.New("Failed to load OM5P Image from resources.")
	}

```

and the ImageView where it's used:

```ImageView{
						Column: 1,
						Row: 0,
						ColumnSpan: 1,
						Image: om5pImg,
					},
```

**Comment by eyotang** [comment]
"om5p.png" should use png.Decode, as following:

pngdata, err := png.Decode(bytes.NewReader(om5p))
om5pImg, err := walk.NewBitmapFromImage(pngdata)
if err != nil {
	fmt.Println("Failed to load OM5P Image from resources.2")
	return 0, errors.New("Failed to load OM5P Image from resources.")
}
