### ISSUE TITLE
Command prompt window still displays

### ISSUE THREAD

**Issue by syncore** [lxn/walk#284]
Is anyone aware of a way to hide the command prompt window? I've built with ldflags="-H windowsgui" and while this does hide the usually persistent cmd prompt window, it still briefly flashes for a few milliseconds on application startup. After using NtTrace on my application, it appears that my application starts up, but another process, C:\Windows\System32\cmd.exe is also launched. The same behavior is not noticed with the walk examples, i.e. the actions example. Only the actions process is started.

**Comment by lxn** [comment]
It doesn't sound like the usual [missing manifest problem](https://github.com/lxn/walk#application-manifest-files), so my second guess would be some weird security product or similar intervention.

**Comment by syncore** [comment]
Dug into this some more using some more. The logrus logging library launches cmd.exe and issues 'ver' to determine the windows version, per https://github.com/sirupsen/logrus/blob/master/terminal_windows.go#L37 so it appears to briefly show the command prompt window even when built with -ldflags="-H windowsgui" since it is launching it as a separate process.

**Comment by lxn** [comment]
Oh, that's pretty horrible. It already calls some functions in kernel32, why not go the whole way and use the appropriate functions to get the version?

Anyway, thanks for letting me know.
