### ISSUE TITLE
Evaluator fails on wv.URL

### ISSUE THREAD

**Issue by kjk** [lxn/walk#291]
This happens when running `webview` sample: `2017/07/09 19:45:04 walk - failed to evaluate expression "'../img/' + icon(wv.URL) + '.ico'": invalid sub expression: "wv",`

I've instrumented the code like this:
```
func (se subExpressions) Get(name string) (interface{}, error) {
	if sub, ok := se[name]; ok {`
		return sub.Value(), nil
	}
	var names []string
	for k := range se {
		names = append(names, k)
	}
	return nil, fmt.Errorf(`invalid sub expression: "%s", names: %v`, name, names)
}
```

And I get: `017/07/09 19:50:16 walk - failed to evaluate expression "'../img/' + icon(wv.URL) + '.ico'": invalid sub expression: "wv", names: [wv.URL]`

So it's close but either the key in `subExpression` is incorrect (should be `wv` and not `wv.URL`) or we should be asking for `wv.URL` and not `wv`.

**Comment by lxn** [comment]
Thanks for reporting!
