### ISSUE TITLE
go get github.com/lxn/walk can't load package: package github.com/lxn/walk: build constraints exclude all Go files in /data/go/src/github.com/lxn/walk

### ISSUE THREAD

**Issue by xingcuntian** [lxn/walk#293]
go get github.com/lxn/walk
can't load package: package github.com/lxn/walk: build constraints exclude all Go files in /data/go/src/github.com/lxn/walk ??

**Comment by lxn** [comment]
Walk is a Windows-only thing, sorry.

**Comment by xingcuntian** [comment]
Thanks, I see
