### ISSUE TITLE
undefined: sort.SliceStable?

### ISSUE THREAD

**Issue by xingcuntian** [lxn/walk#298]
E:\data>go get github.com/lxn/walk
# github.com/lxn/walk
e:\www\golang\src\github.com\lxn\walk\splitterlayout.go:314: undefined: sort.SliceStable

**Comment by kjk** [comment]
You need to use go 1.8 or later. 1.8 is the first version to have sort.SliceStable (https://golang.org/doc/go1.8)

**Comment by xingcuntian** [comment]
@kjk Thanks, I see
