### ISSUE TITLE
go get 的时候提示选择版本

### ISSUE THREAD

**Issue by skiychan** [lxn/walk#299]
go get -u 时提示选择版本；
go get  时提示没有这个go程序

![20170725114144](https://user-images.githubusercontent.com/24283064/28554859-8c14de0c-712e-11e7-8f5a-2055bb5f60e6.png)

**Comment by kjk** [comment]
What does `go version` say?

It looks like you're using a unix shell on Windows, which probably has unix version of go and walk is only supported for windows.

Try doing the same from inside cmd.exe or powershell.

**Comment by skiychan** [comment]
go1.8.3 amd64

最终解决方式是：
1. 删除目录；
2. 因为Go安装在了C盘，卸载了Go，重装安装到D盘；
3. 重新go get 就好了。

可能是由于之前安装过旧的版本（lxn/walk，很久前go get下来过了）
