### ISSUE TITLE
Strange tableview float number separator

### ISSUE THREAD

**Issue by sielaq** [lxn/walk#305]
Hi

I have used example `tableview` with just bigger float number generated (just multiply by `* 100000` not `* 1000`) from example here: https://github.com/lxn/walk/blob/master/examples/tableview/tableview.go#L126
 
then I saw a strange undefined character for big number separator for the `Baz` column like:
![screen shot 2017-08-09 at 14 31 49](https://user-images.githubusercontent.com/7736325/29121595-7f7c9d0a-7d0f-11e7-8e7e-15693b839d78.jpg)

Is it possible to define this character by formatting or something else ?
or this is a bug ?

**Comment by lxn** [comment]
Hi!

Probably the digit grouping symbol in your Windows region settings isn't ASCII, and the relevant code starting at https://github.com/lxn/walk/blob/master/util.go#L39 and https://github.com/lxn/walk/blob/master/util.go#L141 doesn't handle that correctly.

**Comment by sielaq** [comment]
Ok,
thanks a lot for the clue,
I got it now - I have changed that in [ control panel / regional settings / advanced / digit grouping symbol ] for `space`

Actually I still don't know why `half space` (that was the original set) is not working
might be the font settings need to be tweaked.

anyway problem is solved.
