### ISSUE TITLE
Help: How to set background color or img for button

### ISSUE THREAD

**Issue by CodyGuo** [lxn/walk#306]
I tried, but it didn't work

**Comment by lxn** [comment]
Changing the background color of a button is not supported and I'm not sure it should be. ([MSDN](https://msdn.microsoft.com/de-de/library/windows/desktop/bb761849(v=vs.85).aspx) says it would only work for owner-drawn buttons.)

You should be able to set an (not background) image though.

**Comment by CodyGuo** [comment]
thanks.
