### ISSUE TITLE
Notification icons disappear with explorer

### ISSUE THREAD

**Issue by djdv** [lxn/walk#318]
I've been using notification icons and I noticed that they will disappear forever if explorer exits for whatever reason (graceful exit, restart, or crash).

Here's a video demonstrating this with the included example (https://github.com/lxn/walk/tree/master/examples/notifyicon)
http://ipfs.io/ipfs/zDMZof1m6SqXDCrd8XZb7aTgDkiQ6XNa4tpFRajDdgM2PqCDWGxo/Desktop%2009.03.2017%20-%2000.38.55.03-no-audio.mp4

You'll see that the walk application is still running but no longer showing its icon, other applications remain in the tray.

**Comment by djdv** [comment]
for what it's worth I tried adding this
```
	case win.WM_CREATE:
		taskbarRestart := win.RegisterWindowMessage(syscall.StringToUTF16Ptr("TaskbarCreated"))
		if msg == taskbarRestart {
			nid := ni.notifyIconData()
			win.Shell_NotifyIcon(win.NIM_DELETE, nid)
			win.Shell_NotifyIcon(win.NIM_ADD, nid)
		}
	}
```
to the switch here https://github.com/lxn/walk/blob/master/notifyicon.go#L29

after reading this
https://msdn.microsoft.com/en-us/library/windows/desktop/cc144179.aspx#Taskbar_Creation_Not

I'm not getting a hit on WM_CREATE though when restarting explorer.

**Comment by lxn** [comment]
You should probably check for the `taskbarRestart` message in the `default` clause of the `switch`.

**Comment by djdv** [comment]
No luck there, after trying that I tried logging every message that wasn't already handled by the switch, nothing seems to be caught when I restart explorer. Not sure where the issue lies, if the message isn't being sent, if it's getting caught elsewhere, or something else. I am seeing other messages like when I hover over the icon but nothing on (re)launching explorer.

**Comment by lkarlslund** [comment]
You need to do something like this:

```go
var TaskbarRestartMessage uint32
func windowMessageHandler(hwnd win.HWND, msg uint32, wparam, lparam uintptr) (rc uintptr) {
	switch msg {
	case TaskbarRestartMessage:
		// Do icon recovery work here
	case win.WM_CREATE:
		TaskbarRestartMessage = win.RegisterWindowMessage(syscall.StringToUTF16Ptr("TaskbarCreated"))
	....
```

**Comment by zhaoya881010** [comment]
I changed it and it works fine when the explorer crashes. If I need to submit a request?

**Comment by djdv** [comment]
I believe this was resolved by https://github.com/lxn/walk/pull/749
(or potentially something earlier - in any case, notification icons (re)appear on the new taskbar after explorer is restarted)
