### ISSUE TITLE
Can't create single key shortcuts

### ISSUE THREAD

**Issue by jscholes** [lxn/walk#324]
I want to create a menu action with a shortcut of walk.KeyF1, no modifiers.  I tried:

    Shortcut{nil, walk.KeyF1}
    Shortcut{walk.Modifiers{}, walk.KeyF1}
    Shortcut{make(walk.Modifiers), walk.KeyF1}

All resulted in errors.  Is this possible without using a key down event and appending "\tF1" to the action's Text property manually?

**Comment by jordansissel** [comment]
This works for me to have a shortcut act when 'o' is pressed:

 `Shortcut{Key: walk.KeyO}`

Bigger example:

```
	window := MainWindow{
		Title:    "SCREAMO",
		AssignTo: &app.MainWindow,
		MinSize:  Size{Width: 600, Height: 400},
		Layout:   VBox{},
		MenuItems: []MenuItem{
			Menu{
				Text: "&Operations",
				Items: []MenuItem{
					Action{
						Text:     "Hello",
						Shortcut: Shortcut{Key: walk.KeyO},
						OnTriggered: func() {
                                                   println("Hello world")
						},
					},
				},
			},
		},

	}
```

**Comment by jscholes** [comment]
Thanks!  I'm new to Go and didn't think to try that syntax.
