### ISSUE TITLE
How to specify font of TextEdit ?

### ISSUE THREAD

**Issue by tinycedar** [lxn/walk#328]
I've written a tool using your awesome WALK lib, and now I'd like to specify font(especially color) of TextEdit, is it possible to implement it ?

![capture](https://cloud.githubusercontent.com/assets/8019222/18225305/4a399b78-7222-11e6-8e1e-9e0037c63d2b.PNG)

**Comment by lxn** [comment]
You should be able to specify a font, but text color is currently not supported for `[Line|Number|Text]Edit`

```Go
    var le *walk.LineEdit

// snip

    LineEdit{
        AssignTo: &le
        // Either like this
        Font: Font{
            Family: "Segoe UI",
            PointSize: 20,
            Bold: true,
        },
    },

// snip

    // or like that
    font, err := walk.NewFont("Segoe UI", 20, walk.FontBold);
    if err != nil {
        panic(err)
    }

    le.SetFont(font)
```

**Comment by tinycedar** [comment]
@lxn When will be the color to be supported ?

**Comment by lxn** [comment]
Now :-)
