### ISSUE TITLE
Set a window un-resizable

### ISSUE THREAD

**Issue by Litarvan** [lxn/walk#329]
I searched everywhere but didn't find anything to make my main window not resizable, i don't know if i didn't find or if it is missing in the library. Thanks for any answer

**Comment by lxn** [comment]
The only way to do this right now is to use a `Dialog` with `FixedSize`.

**Comment by Litarvan** [comment]
Works perfectly (for those who will read this: remplace "MainWindow" by Dialog, add "FixedSize: true", then if it asks you an "owner" param in .Create()/.Run() just give nil or your main window
