### ISSUE TITLE
TextEdit{Visible:false} still consumes space in VBox{} layout

### ISSUE THREAD

**Issue by tmm1** [lxn/walk#341]
In `BoxLayout`'s `MinSize()` and `Update()`, `shouldLayoutWidget` is not used at all.

**Comment by tmm1** [comment]
Actually both those methods call `widgets()` which does the filtering, so I'm not sure why it's not working correctly..

**Comment by tmm1** [comment]
I'm having a really hard time figuring out how the initial window size is calculated. I have a VBox layout with a lot of buttons, but most of them are invisible. But when the program starts, the size of the window is really tall, as if they are being counted as visible.

**Comment by lxn** [comment]
Please check if https://github.com/lxn/walk/commit/0720a69789e4ca09886384ffb7f7c1080cd49107 fixes this issue.

**Comment by tmm1** [comment]
This works for me now. Thank you very much!
