### ISSUE TITLE
Bind("xxx.Visible") doesn't work

### ISSUE THREAD

**Issue by tmm1** [lxn/walk#342]
I'm trying to bind one PushButton to another PushButton's visible property, but it's not working. Am I doing something wrong?

```golang
PushButton{
  Name:    "aPB",
  Text:    "a",
  Visible: false,
},
PushButton{
  Text:    "b",
  Visible: Bind("aPB.Visible"),
}
```

**Comment by lxn** [comment]
Please check if https://github.com/lxn/walk/commit/e588c2edd385c2d8a3e774a36768c0a9bd83543e fixes your issue.

**Comment by tmm1** [comment]
This works as expected now, thank you!!
