### ISSUE TITLE
Error running the sample test.go on window 10

### ISSUE THREAD

**Issue by chencore** [lxn/walk#348]
OS: window 10
golang: go version go1.9.2 windows/amd64

E:\go_dev\code>test.exe
panic: The specified procedure could not be found.

goroutine 1 [running]:
github.com/lxn/win.MustGetProcAddress(0x7feeefd0000, 0x6357c2, 0xe, 0x7feeeff7548)
        E:/go_dev/work/src/github.com/lxn/win/win.go:57 +0x7d
github.com/lxn/win.init.1()
        E:/go_dev/work/src/github.com/lxn/win/comctl32.go:253 +0x191
github.com/lxn/win.init()
        <autogenerated>:1 +0x5e
github.com/lxn/walk.init()
        <autogenerated>:1 +0x57
main.init()
        <autogenerated>:1 +0x4b

**Comment by kjk** [comment]
Most likely you need to set manifest that specifies latest version of comctrl32.dll library.

See e.g. https://stackoverflow.com/questions/4098076/does-windows-preload-comctrl32-dll-in-an-app or http://ffi.github.io/ruby-ffi-archive/messages/20130928-Re_%5Bruby-ffi%5D%20Function%20_LoadIconMetric_%20not%20found%20in%20%5Bkernel32_%20user32_%20gdi32_%20comctl32%5D%20(FFI__NotFoundError)-1110.html

It looks like it's trying to get address of "LoadIcon" function from comctrl32.dll but without the manifest asking for latest version, you'll get a version of comctrl32.dll that doesn't have this function.

**Comment by chencore** [comment]
Does test.manifest  need to be modified? 
test.manifest:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
	<assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="SomeFunkyNameHere" type="win32"/>
	<dependency>
		<dependentAssembly>
			<assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
		</dependentAssembly>
	</dependency>
</assembly>

**Comment by kjk** [comment]
I don't know if that would fix your problem, but remove `<assemblyIdentity` line.

Manifest that I know works is: https://raw.githubusercontent.com/sumatrapdfreader/sumatrapdf/master/src/SumatraPDF.exe.manifest

**Comment by chencore** [comment]
The problem is solved. Manifest is right.my complie commands is error. my commands  is "go build test.go" ,The right one should be “go build”.
