### ISSUE TITLE
Radio Button Alignment

### ISSUE THREAD

**Issue by Phisatho** [lxn/walk#355]
Is there a way radio-buttons in a groupbox be left aligned? I am getting center aligned for the text making the radio buttons misaligned. The radio button example is also showing similar behaviour if the text lengths for different buttons are different.

Can the radio button's text be positioned on the left of the button?

**Comment by lxn** [comment]
`Grid` aligns widgets differently than `VBox`. Maybe try something like `Layout: Grid{Columns: 1},`.

The layout system should be extended to allow specifying the desired alignment.

The latest changes include support for text on the left side for `CheckBox` and `RadioButton`.

**Comment by Phisatho** [comment]
Grid layout did it. Thanks for the help.

I amd yet to test the TextOnLeftSide property. Will give a feedback later.

**Comment by Phisatho** [comment]
'TextOnLeftSide: true,' works, but spoils the alignment.
I need to find a way to right align the group.
