### ISSUE TITLE
ImageView OnMouseUp callback get wrong value for walk.MouseButton

### ISSUE THREAD

**Issue by juniorfans** [lxn/walk#364]
I have a ImageView put a image in it, and i am interested in mouseUp event on the ImageView, having the code:

![image](https://user-images.githubusercontent.com/18361225/35895764-df011d6e-0bf3-11e8-80f4-c611f4f24a68.png)

but i just get 0 for the button, which presents a invalid mousebutton. why?

**Comment by lxn** [comment]
Thanks for reporting
