### ISSUE TITLE
when I  use  "go get github.com/lxn/walk " ,who can help me?

### ISSUE THREAD

**Issue by gyb33** [lxn/walk#366]
# github.com/lxn/walk
src\github.com\lxn\walk\splitterlayout.go:322: undefined: sort.SliceStable

![qq 20180207184017](https://user-images.githubusercontent.com/23331185/35912179-c8849a28-0c36-11e8-9d2b-577e09b21798.png)

**Comment by kjk** [comment]
What does `go version` say?

`sort.SliceStable` was added in version 1.8, so if you have older version, you need to upgrade Go https://golang.org/dl/

**Comment by gyb33** [comment]
thank you !!

**Comment by gyb33** [comment]
@kjk thank you !! First use github
