### ISSUE TITLE
Always on top and transparent window

### ISSUE THREAD

**Issue by ipamerbg** [lxn/walk#376]
Hi,

1. Is it possible to set the main window to be "always on top" of other windows (in Windows)?
2. Is it possible to make it transparent like 50% when it's inactive and 100% back when it's active?

Thanks

**Comment by lxn** [comment]
Hi!

1. You could try the `BringToTop` method available on any `Window` or use `win.SetWindowPos` directly.
2. That is not supported in walk.

**Comment by ipamerbg** [comment]
Yeah thanks, that's not good for me.
I would like to operate in one window and have the walk one as an overlay on top of the other - which in windowed full screen.
