### ISSUE TITLE
webview javascript function interact with golang function

### ISSUE THREAD

**Issue by waleson** [lxn/walk#381]
Is there any example like :"javascript function/event  in webview"  interact with  "golang func"?

1.golang call the webview javascript function or DOM

2.webview call the golang defined func()

3.only the method by tcpserver/httpserver? 
"direct  call by function "  is possible?

**Comment by lxn** [comment]
All of this sounds useful, but nothing of it is supported, sorry :-(

In my own walk based projects, the only thing I need the `WebView` widget to do is displaying some static HTML. Contributions to this area of walk would be gladly accepted.

**Comment by waleson** [comment]
thank you ,maybe it( webview form ole api) is a complex work. I'm finding  the other ways like go-sciter /directui .

but walk is still useful because its easy.
