### ISSUE TITLE
Can't change label LayoutFlags

### ISSUE THREAD

**Issue by adongy** [lxn/walk#389]
Hi,

I'm trying to right-align a label.

Here is some code to work with:

```
package main

import (
	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
	"github.com/lxn/win"
)

func main() {
	var mw *walk.MainWindow
	MainWindow{
		AssignTo: &mw,
		Size:     Size{300, 300},
		Title:    "_",
		Layout:   Grid{},
	}.Create()

	{
		l, _ := walk.NewLabelWithStyle(mw, win.SS_SUNKEN)
		mw.Layout().(*walk.GridLayout).SetRange(l, walk.Rectangle{X: 0, Y: 0, Width: 1, Height: 1})
		l.SetText("left aligned")
	}

	{
		l, _ := walk.NewLabelWithStyle(mw, win.SS_SUNKEN|win.SS_RIGHT)
		mw.Layout().(*walk.GridLayout).SetRange(l, walk.Rectangle{X: 0, Y: 1, Width: 1, Height: 1})
		l.SetText("right aligned")
	}
	mw.Run()
}
```

(skips most error handling)

Currently, Label.LayoutFlags() is hardcoded to GrowableVert, but not GrowableHorz.

This results in the label width (the horizontal dimension) to be exactly the same as the label length:

![image](https://user-images.githubusercontent.com/95287/39970302-636a8852-56e9-11e8-8b94-272b5bff67c9.png)

Adding GrowableHorz achieves the wanted effect:

![image](https://user-images.githubusercontent.com/95287/39970309-74e7af4c-56e9-11e8-8460-8bcbfb020a91.png)

Is this wanted behavior?

Also, we can't define custom styles using the declarative style, as it enforces walk.NewLabel.
Can we add a `Style uint32` to the `declarative.Label` struct, which keeps the default as-is (0), and use NewLabelWithStyle ?

Best,

**Comment by lxn** [comment]
I would like to avoid exposing low-level stuff like window styles in package `declarative`. It should still be quite easy to add horizontal alignment for a single line of text to `Label`.

It gets more complicated though, when we consider other possible extensions:

-  Vertical alignment
-  Making automatic size computation optional
-  Multi-line text
-  Word wrapping
-  General support for alignment of `Widget`s with `Layout`s

At least support for horizontal alignment for a single line of text should probably be added to `Label` in the short term.

**Comment by adongy** [comment]
Thanks, that does indeed solve my issue if I create a new walk.label + declarative.label.

I would however like to know the reasoning behind not having GrowableHorz but only GrowableVert.

**Comment by lxn** [comment]
Maybe I just forgot to try it, but I don't remember.
