### ISSUE TITLE
Changing the value of a databound property

### ISSUE THREAD

**Issue by npvjN9sMBBo** [lxn/walk#391]
Hello and thanks for the library, it is really good.

When using the databinding, is it possible to force a redraw the GUI when the underlying data has changed?

Take this example

```
type Foo struct {
  A string
}

Label{
  Text: Bind("A"),
}
```

When changing `A`, how can I make the label reflect the new value?

I know I can use SetText, but that would mean maintaining a list of widgets bound to the variable.

Thanks.

**Comment by lxn** [comment]
Hi and thanks for the kind words!

To make this happen, call `Reset` on the `DataBinder`.

**Comment by npvjN9sMBBo** [comment]
Thanks :)
