### ISSUE TITLE
adding a ContextMenu to a NotifyIcon with a **visible** MainWindow causes application to hang

### ISSUE THREAD

**Issue by generaltso** [lxn/walk#403]
steps to reproduce: 
>  - add `mw.SetVisible(true)` to `examples/notifyicon/notifyicon.go` after line `22`
>  - build and run the executable
>  - right-click on the icon in the system tray
>  - click on the main window

I seem to have found a fix though: Passing the parent window's Handle as the value to `hWnd` in `notifyicon.go:90` instead of creating a new window there (but I'm sure there must have been a reason to give it a separate window instance??)

As a diff in case that sentence was confusing:
```
--- a/notifyicon.go
+++ b/notifyicon.go
@@ -87,25 +87,7 @@ type NotifyIcon struct {
 // NewNotifyIcon creates and returns a new NotifyIcon.
 //
 // The NotifyIcon is initially not visible.
-func NewNotifyIcon() (*NotifyIcon, error) {
-       // Create the message-only window for the NotifyIcon.
-       hWnd := win.CreateWindowEx(
-               0,
-               syscall.StringToUTF16Ptr(notifyIconWindowClass),
-               nil,
-               0,
-               0,
-               0,
-               0,
-               0,
-               win.HWND_MESSAGE,
-               0,
-               0,
-               nil)
-       if hWnd == 0 {
-               return nil, lastError("CreateWindowEx")
-       }
-
+func NewNotifyIcon(hWnd win.HWND) (*NotifyIcon, error) {
```

And then doing `systray, err := walk.NewNotifyIcon(mw.Handle())` in user code.

*(actually maybe the diff is more confusing, idk)*

I'm reluctant to submit a PR because again there must have been a reason to not attach the notifyicon to the mainwindow? Also the convention in walk seems to be **not** to pass a `win.HWND` directly so a proper fix would require a few more lines of code...

-tso

**Comment by zx2c4** [comment]
@lxn Any update on this? AFAICT, this is still broken.
