### ISSUE TITLE
Changing the proportions of the widgets in the splitter

### ISSUE THREAD

**Issue by dedalqq** [lxn/walk#423]
I create a new window with a splitter that contains two windows (as in the example on the main page). But I want the size of the elements in the splitter not to be 50/50.

Is there any way to do this?
I have not found a way.

Thank you.

**Comment by lxn** [comment]
You may try `MaxSize`, `MinSize` or `StretchFactor`. If you need one of your widgets to stay at the size the user resized it to, you can use `yourSplitter.SetFixed(yourFixedWidget, true)`.

Hope this helps...

**Comment by dedalqq** [comment]
If I use MaxSize, MinSize or SetFixed, then in this case there won't be much point in the splitter itself = (

And what is the `StretchFactor`? I do not understand

**Comment by lxn** [comment]
Did you try it and it had no effect?

This should make the `TableView` four times as wide as the `TreeView` initially. Can't try it myself right now though.

```Go
...
HSplitter{
    Children: []Widget{
        TreeView{
            StretchFactor: 1,
        },
        TableView{
            StretchFactor: 4,
        },
    },
},
...
```

**Comment by dedalqq** [comment]
Great, this is exactly what I was looking for, thanks a lot =)
