### ISSUE TITLE
An offer: lock system's UI thread to improve FPS

### ISSUE THREAD

**Issue by fpawel** [lxn/walk#425]
### General description of the problem
walk application works noticeably slowly than destop application without GC. Its performance is comparable to performance of Java / C # desktop application. 
### Assumption
This may be due to the peculiarities of Go language runtime - the rendering thread is intermittently interrupted by other, less important, gorutines. As a result, there are micro pauses in the program.
### Оffering
Bind the [main event loop](https://github.com/lxn/walk/blob/master/form.go#L380) gorutine to its system thread with [LockOSThread](https://golang.org/pkg/runtime/#LockOSThread), i.e. actually use gorutine as a thread. I believe this should significantly improve performance.

**Comment by lxn** [comment]
Thanks, but that's already taken care of here: https://github.com/lxn/win/blob/master/win.go#L16

Bad performance with walk I would expect to stem from the layout system, overusing gradients or other backgrounds, extensive use of `Bind`, or just from the high FFI overhead of Go: https://github.com/dyu/ffi-overhead

Do you notice especially bad performance, maybe related to some specific widget types?

**Comment by fpawel** [comment]
@lxn, thank you for the clarification. I realy did not know about [this](https://github.com/lxn/win/blob/master/win.go#L16). 
Yes of course. Noticeable performance degradation occurs when using complex layouts and TableView.
