### ISSUE TITLE
Can you achieve the effect of code hints

### ISSUE THREAD

**Issue by CodyGuo** [lxn/walk#426]
Can you achieve the effect of code hints?
As shown below:

![default](https://user-images.githubusercontent.com/10672966/48880509-c8958480-ee4b-11e8-9244-87421eb30801.png)

**Comment by lxn** [comment]
You probably would need an owner-drawn popup menu to achieve this. As there currently is no support for owner-drawn menus in walk, you might try using a `TableView` (see tableview example for styling) with a single column and with hidden header. It wouldn't look and feel exactly the same though and you currently would have to do the popup behavior yourself.
