### ISSUE TITLE
FileDialog with OFN flags

### ISSUE THREAD

**Issue by jackyzy823** [lxn/walk#427]
First of all, thanks for your excellent work!

I'm using `FileDialog` from `commondialogs.go` and i want to use `FileDialog` with flag such as `OFN_OVERWRITEPROMPT` to implment a SaveFileDialog.

However  `func (dlg *FileDialog) ShowSave`  could not receive flags and  `func (dlg *FileDialog) show` is  an unexported function though it receives flags.

So could we make a new function such as  `func (dlg *FileDialog) ShowSaveWithFlags(owner Form ,flags uint32)`  (and for `ShowOpen` ... ) to not break current API stability and export flags such as OFN_OVERWRITEPROMPT from `lxn/win`   .

Or could we add a `Flag` field into `FileDialog` struct ?

**Comment by lxn** [comment]
Thanks for the kind words :-)

You can now use the `Show` method directly.

**Comment by lxn** [comment]
Changed my mind, your suggestion adding a Flags field seems preferable.
