### ISSUE TITLE
panic when removing tabpage if there's only one

### ISSUE THREAD

**Issue by jackyzy823** [lxn/walk#428]
Code to reproduct:
```go
package main

import (
	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)


func main() {
	var nW *walk.MainWindow
	var tab *walk.TabWidget

	MainWindow{
		AssignTo: &nW,
		MinSize:  Size{1000, 400},
		Layout:   VBox{},
		Children: []Widget{
			TabWidget{
				AssignTo: &tab,
				Pages: []TabPage{
					TabPage{
						Title: "page 0",
					},
				},
			},
			PushButton{
				Text: "del",
				OnClicked: func() {
					tab.Pages().RemoveAt(0)
				},
			},
		},
	}.Run()
}
```

error log
```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/lxn/walk.(*TabPageList).At(...)
	...src/github.com/lxn/walk/tabpagelist.go:36
github.com/lxn/walk.tabWidgetTabWndProc(0x53088c, 0xf, 0x0, 0x0, 0x0)
	...src/github.com/lxn/walk/tabwidget.go:422 +0xd99
syscall.Syscall(0x775d6680, 0x2, 0x1040772, 0xc0000650e0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/runtime/syscall_windows.go:172 +0xf9
github.com/lxn/win.IsDialogMessage(0x1040772, 0xc0000650e0, 0x0)
	...src/github.com/lxn/win/user32.go:2387 +0x64
github.com/lxn/walk.(*FormBase).Run(0xc00002f180, 0x0)
	...src/github.com/lxn/walk/form.go:397 +0x117
github.com/lxn/walk/declarative.MainWindow.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	...src/github.com/lxn/walk/declarative/mainwindow.go:202 +0xd7
```

in `tabwidget.go` line `421`
https://github.com/lxn/walk/blob/0960bf64789fc2207251724706c793ad853d8144/tabwidget.go#L421

i change it to 
```
if tw.currentIndex != -1 && tw.currentIndex < tw.pages.Len(){
``` 

it works,but i'm not sure what else would happen.

Just for your reference.

After some investigation , i found that when the last tab removed.the value `tw.currentIndex` become 4294967295 which is 0xffffffff .It seems like a integral overflow?

**Comment by jackyzy823** [comment]
https://github.com/lxn/walk/blob/0960bf64789fc2207251724706c793ad853d8144/tabwidget.go#L296

int treat 0xffffffff as a positive number.
so it should be
```tw.currentIndex = int(int32(win.SendMessage(tw.hWndTab, win.TCM_GETCURSEL, 0, 0)))```

**Comment by lxn** [comment]
Good catch! Thanks for the nice report and research.

Do you want to send a pull request, or should I just commit your fix? If you want to send a PR, please also add yourself to the AUTHORS file.

**Comment by jackyzy823** [comment]
you can just commit this fix.
