### ISSUE TITLE
the implement of manifest.go may be wrong

### ISSUE THREAD

**Issue by jackyzy823** [lxn/walk#444]
After some investigation for the problem `TTM_ADDTOOL` in #399 .I found that this problem may be caused by wrong struct cbsize of `win.TOOLINFO` 

According to MSDN documents [structure-sizes-for-different-common-control-versions](https://docs.microsoft.com/en-us/windows/desktop/controls/common-control-versions#structure-sizes-for-different-common-control-versions) ,toolinfo has different struct size in different comctl version.

In manifest.go. we force to use Version 6. But there's a problem  that in `lxn/win` we load library comctl32.dll before this manifest actives via `ActivateActCtx`. So In memory there's two  comctl32.dll ( version 6 is loaded via manifest . and another is loaded via `lxn/win` libcomctl.

Here's my running app with `lxn/walk` 
![comctl](https://user-images.githubusercontent.com/2900871/51248954-b3ad1b80-19cc-11e9-80df-bb92979c95dd.png)

if you have a static appname.manifest file in the same folder, only version 6 dll will be loaded.

So there maybe several kinds of approachs.
1. ActivateActCtx before `lxn/walk` libcomctl loaded , this will affect `lxn/win`
2. Or we can use comctl32.`DllGetVersion` to get version to handle TOOLINFO struct size only. Not very sure if other codes woud be affected by this problem.
3. Just move back to generate mainfest file manually.

**Comment by zx2c4** [comment]
There's an additional problem with manifest.go too: that temporary directory in some circumstances might not be very safe, allowing an attacker to stick a malicious manifest there. I'd recommend getting rid of the manifest.go hack and reverting to the old method.
