### ISSUE TITLE
Unable to scroll down listview programmatically

### ISSUE THREAD

**Issue by fpawel** [lxn/walk#453]
This code does not do it:
```
import(
        "github.com/lxn/walk"
	"github.com/lxn/win"
	"golang.org/x/sys/windows"
)

var tableView *walk.TableView
//
si := new(win.SCROLLINFO)
win.GetScrollInfo(tableView.Handle(), win.SB_VERT, si)  // returns false
windows.GetLastError()  // returns nil
si.NPos = si.NMax
win.SetScrollInfo(x.tableView.Handle(), win.SB_VERT, si, true) // returns 0 and do nothing
```
Perhaps I do wrong. Please suggest a solution for how to do it correctly.

**Comment by lxn** [comment]
Sorry for the late response. This should be fixed by https://github.com/lxn/walk/commit/bf929d66e944e31cd3f7cd802a697c62bc5b2006.

The code you tried doesn't work, because since implementing frozen columns, `TableView` doesn't map to a win32 list view any more, but instead contains two of them.

**Comment by fpawel** [comment]
@lxn, no problems. Thanks, it's realy fixed.
