### ISSUE TITLE
Vertical slider in upper position is lower value

### ISSUE THREAD

**Issue by ogau** [lxn/walk#460]
1. How to swap values, or how to turn off the pop-up pointer to the current value?
![image](https://user-images.githubusercontent.com/25056868/53300478-ae63ac00-3869-11e9-83e9-56674fbfe180.png)
2. How to exclude the space between two containers? But it is also necessary that TableView could expand when the window size was changed. I need a similar effect as if I swap two containers in this code, need only an expanding table.
```
package main

import (
	. "github.com/lxn/walk/declarative"
)

func main() {
	MainWindow{
		Layout: VBox{SpacingZero: true, MarginsZero: true},
		Size:   Size{Height: 400, Width: 400},
		Children: []Widget{
			Composite{
				Layout: Flow{},
				Children: []Widget{
					Composite{
						Border: true,
						Layout: HBox{},
						Children: []Widget{
							Slider{
								Orientation: Vertical,
								MinSize:     Size{Height: 120},
							},
						},
					},
				},
			},
			Composite{
				Layout: Grid{},
				Children: []Widget{
					Label{
						Text: "Text",
					},
					TableView{
						RowSpan: 2,
						Column:  1,
					},
					VSpacer{Row: 1},
				},
			},
		},
	}.Run()
}
```
![image](https://user-images.githubusercontent.com/25056868/53303558-79695080-388d-11e9-81cb-c0b2c07f4f5d.png)

**Comment by huggabeats** [comment]
The problem is that without the use of the Flow Layout, the size of the vertical slider begins to change along with the window.

**Comment by huggabeats** [comment]
I commented out the flag in the source code and it all worked as it should. Can the absence of this flag somehow affect the work applications?
```
func (l *FlowLayout) LayoutFlags() LayoutFlags {
	return ShrinkableHorz | ShrinkableVert | GrowableHorz | GrowableVert | GreedyHorz  // | GreedyVert
}

```

**Comment by lxn** [comment]
With the latest commits, you can do it like this:

```Go
package main

import (
	. "github.com/lxn/walk/declarative"
)

func main() {
	MainWindow{
		Layout: Grid{Columns: 2},
		Size:   Size{Height: 400, Width: 400},
		Children: []Widget{
			Composite{
				ColumnSpan: 2,
				Border:     true,
				Layout:     HBox{},
				Children: []Widget{
					Slider{
						Orientation:    Vertical,
						MinSize:        Size{Height: 120},
						ToolTipsHidden: true,
					},
				},
			},
			Label{
				Text: "Text",
			},
			TableView{},
		},
	}.Run()
}
```

**Comment by huggabeats** [comment]
Problem repeats if you append VSpacer{} to container include vertical Slider. Also if this is a nested container having VSpacer{}.

**Comment by huggabeats** [comment]
Is it possible in future that you implement a slider with an instant transition to a mouse click (now it moves by 25%)? Or how can do it yourself?
Sorry for so many questions for the slider, it's just important for my GUI.

**Comment by lxn** [comment]
No worries!

Layout in walk certainly isn't perfect. Will have a deeper look tomorrow.

Instant transition should be possible: https://docs.microsoft.com/en-us/windows/desktop/controls/tbm-setpagesize

**Comment by lxn** [comment]
The latest changes should fix your issue. `Spacer` now has a new `GreedyLocallyOnly` option:

```Go
package main

import (
	. "github.com/lxn/walk/declarative"
)

func main() {
	MainWindow{
		Layout: Grid{Columns: 2},
		Size:   Size{Height: 400, Width: 400},
		Children: []Widget{
			Composite{
				ColumnSpan: 2,
				Border:     true,
				Layout:     HBox{},
				Children: []Widget{
					Slider{
						Orientation:    Vertical,
						MinSize:        Size{Height: 120},
						ToolTipsHidden: true,
					},
					Composite{
						Layout: VBox{},
						Children: []Widget{
							VSpacer{GreedyLocallyOnly: true},
							Label{Text: "First row"},
							Label{Text: "Second row"},
						},
					},
				},
			},
			Label{
				Text: "Text",
			},
			TableView{},
		},
	}.Run()
}
```

**Comment by lxn** [comment]
Oh I forgot to mention `Slider.PageSize`. Just set it to the same value as `MaxValue` for instant transition on click.

**Comment by huggabeats** [comment]
> Oh I forgot to mention `Slider.PageSize`. Just set it to the same value as `MaxValue` for instant transition on click.

I saw that you also added support for line size, superb!
