### ISSUE TITLE
Proposal, fix inconsistent  design of  layout methods in "walk\declarative\layouts.go"

### ISSUE THREAD

**Issue by StephanVerbeeck** [lxn/walk#465]
* The design of layouts in "\go\src\github.com\lxn\walk\declarative\layouts.go" is inconsistent.
* Fix error in placing and resizing calculation of child widgets.

There are 3 main methods of placing children []Widget in a rectangular GUI area.
1) Box, make a row (left to right) or column (top to bottom) of the child widgets
2) Grid, like box but with multiple rows or multiple columns, support spanning multiple cells.
4) Flow, like text left to right until available width reached and then start new row with same logic until all children are placed.

The inconsistency is that there is NO REASON why Box allows the preference of placement horizontal or vertical and that Grid and Flow do not allow this.
With Flow we also need the ability to first fill column 1 then column 2 etc (now we fill first row 1 then row 2 etc).
With Grid we also need the ability to fill column by column (now only row by row).

The error in placing is that all 3 models now only work correct inside a ScrollView.
When placed inside another container (e.g. Composite) then the layout always fill all the available room even when this violates the given max size of the children.  There is no logical or technical reason why the layout is able to leave unused room in a scroll view and does not do this inside other containers.

For the moment I avoid the bug by, even in dialog boxes, placing all children inside a scrollview.
This workaround should not be needed, given max sizes of e.g. push buttons should be respected.

**Comment by StephanVerbeeck** [comment]
For backward compatibility the Grid and Flow should remain but only get an extra item "Direction".
*
 The new HGrid and VGrid then extend Grid (merely filling in the extra Direction field).
* The new HFlow and VFlow then extend Flow (merely filling in the extra Direction field).

* HGrid works the same as Grid now.
* HFlow works the same as Flow now.

**Comment by StephanVerbeeck** [comment]
All 3 methods Box, Grid and Flow should get an extra field "Placement" which is an enum of 9 possible values being 

* PlaceLeftTop (default)
* PlaceCenterTop
* PlaceRightTop
* PlaceLeftCenter
* PlaceCenter
* PlaceRightCenter
* PlaceLeftBottom
* PlaceCenterBottom
* PlaceRightBottom

Name giving of these constants is by order X,Y (same order as common used in 2D coordinates)

The extra field Placement declares at which side, horizontal and vertical, the free unused space should go.
For the HFlow this placement corresponds to the effect or left or right aligning text (imagine that a widget was a word).

**Comment by lxn** [comment]
You can use `Layout: Grid{Rows: 2}` the same as `Layout: Grid: Columns: 2`. Just don't combine them.

Flow is a pretty recent development. For the time being I only implemented the direction that is available now. Do you have a real usecase where you need some other direction?

Yesterday I added support for `Alignment` per `Layout` and also per `Widget`.

**Comment by StephanVerbeeck** [comment]
The use-case was a tab-page for settings which contains separate boxes where each group contains the controls of a single aspect of the accounting application.  Given the space available I found it unprofessional looking that text fields could be resized to +3000 pixels.  So I placed each group of controls inside a Groupbox.  So the hierarchy for a setting is:

MainWindow->HSplitter->TabWidget->TabPage->ScrollView->GroupBox->Label+LineEdit

where the GroupBox uses a grid layout and the ScrollView uses a Flow layout.
Only with this setup could I reach the desired effect that the LineEdit's would not be resized to extreme horizontal dimensions (the MaxSize attribute does not work).

As to the fix for Placing the use-case is that I want my push buttons to group at the right side of the screen inside a Composite with Flow layout (not HBox because if there are too many buttons for the horizontal available width I want them to automatically regroup in multiple rows (and only Flow layout can do that).

The existing system would be able to do what I want too if there were such a thing as a "Filler" (to take up the unused space, but I think that would not be the right answer to the missing functionality).

I am new to Go and Walk and struggling with simple things (like how ridiculous complex it is to insert or remove an item from an array, e.g. (look at the bug in EditPost that inserts the record 2x instead of 1x)

	package main

	import (
		"sort"

		"github.com/lxn/walk"
		. "github.com/lxn/walk/declarative"
	)

	var postBinder *walk.DataBinder
	var postTableView *walk.TableView
	var postModel = NewPostModel()

	func PostTableView() Widget {
		return TableView{
			Name:                  "PostTableView",
			AssignTo:              &postTableView,
			AlternatingRowBGColor: walk.RGB(240, 240, 240),
			ColumnsOrderable:      false,
			Columns: []TableViewColumn{
				{Name: "id", Title: "id"},
				{Name: "name", Title: "name"},
			},
			Model:           postModel,
			OnItemActivated: EditPost,
			OnKeyUp: func(key walk.Key) {
				switch key {
				case walk.KeyInsert:
					InsertPost()
				case walk.KeyDelete:
					DeletePost()
				}
			},
			ContextMenuItems: []MenuItem{
				Action{Text: "Edit", OnTriggered: EditPost},
				Action{Text: "Insert", OnTriggered: InsertPost},
				Action{Text: "Delete", OnTriggered: DeletePost},
			},
		}
	}

	type PostModel struct {
		walk.SortedReflectTableModelBase
		items []Post
	}

	var _ walk.ReflectTableModel = new(PostModel) // check interface

	func NewPostModel() *PostModel {
		model := &PostModel{}
		model.ResetRows()
		return model
	}

	func EditPost() {
		if index := postTableView.CurrentIndex(); index > -1 {
			RunPostDialog(&postModel.items[index])
		}
	}

	func InsertPost() {
		newItem := Post{}
		RunPostDialog(&newItem)
		i := postTableView.CurrentIndex()
		postModel.items = append(append(postModel.items[:i], newItem), postModel.items[i:]...)
		postModel.PublishRowsInserted(i, i)
		postTableView.SetCurrentIndex(i)
	}

	func DeletePost() {
		i := postTableView.CurrentIndex()
		if i >= 0 && AskConfirm(mainWindow, "Delete this post") {
			postModel.items = append(postModel.items[:i], postModel.items[i+1:]...)
			postModel.PublishRowsRemoved(i, i)
			postTableView.SetCurrentIndex(i)
		}
	}

	func (model *PostModel) Items() interface{} {
		return model.items
	}

	// Called by the TableView from SetModel and every time the model publishes a
	// RowsReset event.
	func (model *PostModel) RowCount() int {
		return len(model.items)
	}

	// Called by the TableView when it needs the text to display for a given cell.
	func (model *PostModel) Value(row, col int) interface{} {
		item := model.items[row]

		switch col {
		case 0:
			return item.Short
		case 1:
			return item.Long
		default:
			return nil
		}
	}

	func (model *PostModel) ResetRows() {
		// Create some random data.
		model.items = make([]Post, len(DefaultPosts))

		for i, post := range DefaultPosts {
			model.items[i] = post
		}

		// Notify TableView and other interested parties about the reset.
		model.PublishRowsReset()

		model.Sort(model.SortedColumn(), model.SortOrder())
	}

	// Sort is called by the TableView to sort the model.
	func (model *PostModel) Sort(col int, order walk.SortOrder) error {
		sort.SliceStable(model.items, func(i, j int) bool {
			a, b := model.items[i], model.items[j]

			c := func(ls bool) bool {
				if order == walk.SortAscending {
					return ls
				} else {
					return !ls
				}
			}

			switch col {
			case 0:
				return c(a.Short < b.Short)

			case 1:
				return c(a.Long < b.Long)
			}

			panic("unreachable")
		})

		return model.SorterBase.Sort(col, order)
	}

**Comment by lxn** [comment]
It sounds like you want `[H|V]Spacer`, which is used to take up excessive space.

**Comment by StephanVerbeeck** [comment]
I started to use the spacers and it solves the formatting problems.
(Issue may be closed)
