### ISSUE TITLE
Text Alignment2d into LineEdit not working

### ISSUE THREAD

**Issue by ogau** [lxn/walk#466]
```
LineEdit{
	Text:      "Text",
	Alignment: // Any align2d type not work,
}
```

**Comment by lxn** [comment]
Yeah sorry, I changed this last week. Before the change, `LineEdit` and `TextEdit` both had `Alignment Alignment1D`. Not only was this inconsistent with `Label.TextAlignment`, it also interfered with the introduction of alignment in general layout. Long story short, now there is `Widget.Alignment` for general layout and `TextAlignment` for text layout.
