### ISSUE TITLE
After a TextEdit box is loaded it is scrolled down. Can it be scrolled up after it is loaded?

### ISSUE THREAD

**Issue by tectwc** [lxn/walk#468]
My TextEdit box is defined with VScroll: true. The TextEdit box is loaded with the following code. After it is loaded the TextEdit box is scrolled all the way down. Is it possible to scroll the TextEdit box all the way up after it is loaded in the program code. Thank you.

out4TE.SetText("")
for k := range resultSet {
   if resultSet[k] > " " {
       out4TE.AppendText(resultSet[k]+"\n"
    }
}

**Comment by lxn** [comment]
You can use the new `ScrollToCaret` method like this:

```Go
...
out4TE.SetTExtSelection(0, 0)
out4TE.ScrollToCaret()
...
```

**Comment by tectwc** [comment]
Thank you!

**Comment by majimboo** [comment]
Would also be great to have a scroll to bottom helper. I'm currently doing it like this:

    te.SendMessage(win.EM_SCROLL, win.SB_BOTTOM, 0)
