### ISSUE TITLE
No visible EventPublisher on Window

### ISSUE THREAD

**Issue by adongy** [lxn/walk#474]
Hi,

Seems like Window hides its visibleChangedPublisher, making it hard to update a window when it gets shown to the user.

Is it possible to expose it? Visible() is already taken by the boolean value, so maybe VisibleEvent? I can make the pull request if needed.

Or is there another way I haven't seen?

Thanks.

**Comment by lxn** [comment]
You could previously use `widget.Property("Visible").Changed().Attach(...)`, but that is kind of a hack.
