### ISSUE TITLE
My GUI program doesn't work.

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#475]
OS：Windows 10
Version：10.0.17763（v1809）
Go Version：1.12.1

Stopped running after "go run main.go" and no errors were reported.

**Comment by iquanxin** [comment]
In the build directory, you need to include the *.manifest and rsrc.syso files.

**Comment by HeyDon-Lee** [comment]
Thank you! @iquanxin 

I see the GUI program.
