### ISSUE TITLE
How to keep HSplitter fixed

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#476]
```go
	window, _ := walk.NewMainWindow()
	window.SetTitle(``)
	window.SetWidth(400)
	window.SetHeight(200)
	vbox := walk.NewVBoxLayout()
	vbox.SetMargins(walk.Margins{
		HNear: 4,
		VNear: 4,
		HFar:  4,
		VFar:  4,
	})
	window.SetLayout(vbox)

	bit32, _ := walk.NewPushButton(window)
	bit32.SetText(``)

	bit64, _ := walk.NewPushButton(window)
	bit64.SetText(``)

	button_list, _ := walk.NewHSplitter(window)
	button_list.Children().Add(bit32)
	button_list.Children().Add(bit64)

	tip, _ := walk.NewLabel(window)
	tip.SetText(``)

	window.Children().Add(button_list)
	window.Children().Add(tip)
	window.Show()
	window.Run()
```

This is my code, but HSplitter moves left and right.

**Comment by HeyDon-Lee** [comment]
I'm just getting started with lxn/walk. I don't know much about it.

**Comment by HeyDon-Lee** [comment]
How does HSplitter set to fill the remaining window space.

**Comment by HeyDon-Lee** [comment]
How PushButton sets clicked events?

**Comment by adongy** [comment]
Try to use
```
	button_list, _ := walk.NewComposite(window)
        button_list.SetLayout(walk.NewHBoxLayout())
        walk.NewHSpacer(button_list)
	button_list.Children().Add(bit32)
	button_list.Children().Add(bit64)
```

**Comment by HeyDon-Lee** [comment]
> Try to use
> 
> ```
> 	button_list, _ := walk.NewComposite(window)
>         button_list.SetLayout(walk.NewHBoxLayout())
>         walk.NewHSpacer(button_list)
> 	button_list.Children().Add(bit32)
> 	button_list.Children().Add(bit64)
> ```

Composite can't resize the button.

**Comment by HeyDon-Lee** [comment]
How do I turn off the window minimize and maximize buttons?

**Comment by HeyDon-Lee** [comment]
There's a ui.NewGrid in github.com/andlabs/ui that fits my mind, but github.com/andlabs/ui compiles exe three times larger than github.com/lxn/walk, and I don't really want to use it.

**Comment by adongy** [comment]
Do you want the 2 buttons to take the full width? In that case remove the spacer.

**Comment by HeyDon-Lee** [comment]
@adongy 
Yes, but the two buttons do not automatically fill the entire Composite control. Includes setting the size of buttons and Composite. 

I set up MinMaxSize, too. it's no use.

**Comment by adongy** [comment]
I don't understand what you're trying to achieve. Can you explain what is the expected output, as well as what you experience?

**Comment by HeyDon-Lee** [comment]
![](https://user-images.githubusercontent.com/16282726/55037980-60a1b580-505a-11e9-92d6-5d57f9a7e19a.jpg)

The left side of the picture is caused by Composite's inability to change the size of the button. 
But what I want to do is the effect on the right side of the picture.

**Comment by lxn** [comment]
You could do it like this, but you would enter the world of pain of doing all layout yourself:

```Go
package main

import (
	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

func main() {
	var mw *walk.MainWindow
	var lbl *walk.Label
	var pb1, pb2 *walk.PushButton

	MainWindow{
		AssignTo: &mw,
		MinSize:  Size{400, 200},
		Children: []Widget{
			PushButton{
				AssignTo: &pb1,
				Text:     "Button 1",
			},
			PushButton{
				AssignTo: &pb2,
				Text:     "Button 2",
			},
			Label{
				AssignTo:   &lbl,
				ColumnSpan: 2,
				Text:       "Label 1",
			},
		},
		OnSizeChanged: func() {
			cb := mw.ClientBounds()

			b := walk.Rectangle{0, 0, cb.Width / 2, cb.Height - 20}
			pb1.SetBounds(b)

			b.X += b.Width
			pb2.SetBounds(b)

			lbl.SetBounds(walk.Rectangle{10, b.Height, cb.Width - 20, 20})
		},
	}.Run()
}
```

Maybe I'll add some better way to do it, but don't have the time right now.

**Comment by HeyDon-Lee** [comment]
@lxn 
How do I hide maximized and minimized buttons?

**Comment by HeyDon-Lee** [comment]
@lxn 
How to compile pictures, sounds and other resources into exe programs? 

This is my last question.

**Comment by lxn** [comment]
I haven't used anything like this myself, but you may want to give https://github.com/gobuffalo/packr a try.

**Comment by StephanVerbeeck** [comment]
You can extract from this example.
Please note that it does not work properly (related to maximize and restore it does not stay fixed).
It also helps if you save the GUI size and position (e.g. var walkSettings = walk.NewIniFileSettings("GUI_Settings.ini") )




	var com [3]*walk.Composite

...

			HSplitter{
				Name:     "Splitter",
				AssignTo: &splitter,
				Children: []Widget{
					Composite{
						AssignTo: &com[0],
						Layout:   VBox{SpacingZero: true, MarginsZero: true},
						MinSize:  Size{100, 400},
						MaxSize:  Size{400, 4096},
						Children: []Widget{
							Label{Text: "Directories (Periods)"},
							DirTreeView(),
						},
					},
					Composite{
						Name:     "Files",
						AssignTo: &com[1],
						Layout:   VBox{SpacingZero: true, MarginsZero: true},
						MinSize:  Size{150, 400},
						MaxSize:  Size{600, 4096},
						Children: []Widget{
							Label{AssignTo: &filesLabel, Text: "Files (Documents)"},
							FileTableView(),
						},
					},
					Composite{
						Name:     "Bookings",
						AssignTo: &com[2],
						Layout:   VBox{SpacingZero: true, MarginsZero: true},
						MinSize:  Size{150, 400},
						MaxSize:  Size{600, 4096},
						Children: []Widget{
							Label{AssignTo: &bookingLabel, Text: "Bookings"},
							BookingTableView(),
						},
					},

...

				},
			},
		},
	}.Create()
	if err != nil {
		return err
	}
	for i := range com {
		splitter.SetFixed(com[i], true) // prevent splitter from moving proportional to mainWindow width
	}
	mainWindow.Run()

**Comment by HeyDon-Lee** [comment]
@StephanVerbeeck 
So terrific!

Sorry, I'm late for the reply. I have some things to deal with before. I haven't had time to see Github.

**Comment by HeyDon-Lee** [comment]
@lxn 
gobuffalo/packr/v2 is really good.

1. I would like to ask how to set the picture as a background picture of the window? 
1. How do I set the opacity of the button's background color?
1. How do I set the font color of a control?

**Comment by lxn** [comment]
1.

```Go
...
	Background: BitmapBrush{
		Image: "file path or resource name", // or numeric resource id or whatever
	},
...
```

2. This isn't supported, sorry.

3. If a widget supports it, it is via `TextColor`.

**Comment by HeyDon-Lee** [comment]
@lxn 
What if the control that sets the font color is PushButton?

**Comment by HeyDon-Lee** [comment]
Don't tell me I can only superimpose PushButton with a changed font color Label.

**Comment by lxn** [comment]
Custom text color for a `PushButton` should be possible to implement using owner drawing, but I am currently too short on time to even try it, sorry :(

**Comment by HeyDon-Lee** [comment]
@lxn Does GridLayer have a code example? I tried several times and failed.

**Comment by HeyDon-Lee** [comment]
How does TextEdit's KeyDown (). Attach () recognize which button was pressed?

**Comment by StephanVerbeeck** [comment]
> 1. How does TextEdit's KeyDown().Attach() recognize which button was pressed?（I don't know how to use this method to get keyCode.）

It does not, you have to add an IF or SWITCH statement in the attached function to check and perform the corresponding action for each key press or combination of key presses you want to recognize.
e.g.

	func oKey(key walk.Key) {
		if key == walk.KeyO && walk.AltDown() && walk.ControlDown() && walk.ShiftDown() {
			// ...
		}
	}

> 2. How is TextEdit set to one line?

It does not, you should use LineEdit{} versus TextEdit{} for  multiline vs single-line input

> 3. How is TextEdit text alignment centered?

LineEdit{Alignment: walk.AlignHCenterVCenter}

**Comment by HeyDon-Lee** [comment]
2. ![image](https://user-images.githubusercontent.com/16282726/56985769-af8fbd00-6bbb-11e9-9a6f-b0bb21d8b2b9.png) OK.
2. The Alignment property is invalid.

**Comment by StephanVerbeeck** [comment]
> 2. The Alignment property is invalid.

Yes, I was a bit quick answering (did not test the intended effect)

	urlEdit.SetAlignment(walk.AlignHCenterVNear) // Set alignment of widget in container
	urlEdit.SetTextAlignment(walk.AlignCenter) // set alignment of text in widget

**Comment by HeyDon-Lee** [comment]
@StephanVerbeeck 
Thank you!

**Comment by HeyDon-Lee** [comment]
@StephanVerbeeck 
How do I use walk.NewGridLayout()?
I want to use walk.NewGridLayout() to dynamically load a certain number of buttons.

**Comment by StephanVerbeeck** [comment]
> How do I use walk.NewGridLayout()?
> I want to use walk.NewGridLayout() to dynamically load a certain number of buttons.

Please start a new issue (next time) when you change the subject to a complete different question.
For the answer to this new question check https://github.com/lxn/walk/issues/373 and https://github.com/lxn/walk/issues/419 (which is what you were looking for)
