### ISSUE TITLE
How to use FileDialog?

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#478]
I want to open File Dialog to select a text file, but Filter, FilterIndex, Flags three parameters are a little unclear, can you give me an example.

**Comment by lxn** [comment]
Please have a look at the imageviewer example.

**Comment by HeyDon-Lee** [comment]
@lxn 
I see. 

But I have a question. why don't these instances provide full code, but a mixture of data structures and code?

**Comment by lxn** [comment]
If memory serves this was done because I don't like functions with loads of parameters and some of them even optional.
