### ISSUE TITLE
How to use database?

### ISSUE THREAD

**Issue by iquanxin** [lxn/walk#479]
Use the database in the project, compile and package, can not run the software on the client computer.

`_ "github.com/go-sql-driver/mysql"
"github.com/jmoiron/sqlx"`

**Comment by kjk** [comment]
It's not related to walk library. You'll have better luck asking such questions on https://stackoverflow.com/

Also, provide more details, like what exactly is the problem.

**Comment by iquanxin** [comment]
ok, thanks
