### ISSUE TITLE
TableView doesn't properly inherit font size from window

### ISSUE THREAD

**Issue by kjk** [lxn/walk#480]
Consider this very simplified form:
```
fontDef := declarative.Font{
    Family:    "MS Shell Dlg 2",
    PointSize: 20,
}

mainTmpl := declarative.MainWindow{
    Font:     fontDef,
    Layout: declarative.VBox{
        MarginsZero: true,
        SpacingZero: true,
    },
    Children: []declarative.Widget{
        declarative.TableView{
        },
    },
}
```
I've declared a large font that I set on `MainWindow` but **not** on `TableView` that is a child on that window.

I get:

![image](https://user-images.githubusercontent.com/7935/55213277-0ca8e500-51b0-11e9-87ee-18e763b13499.png)

`TableView` properly inherits the font from the window but doesn't adjust the size of the row accordingly.

This can be easily fixed by setting the font explicitly on `TableView` so it's not a big deal but it does look like a bug and other controls (LineEdit, Label, ListView) work properly.

**Comment by lxn** [comment]
Thanks for reporting!
