### ISSUE TITLE
Sporadic Crash at form.go#432

### ISSUE THREAD

**Issue by StephanVerbeeck** [lxn/walk#483]
I see now and then a program crash.
It is not systematic but can not be captured (no automatic recovery) and for a commercial program this is not good (as I can not fix it).

I would love to fix it myself but have no idea yet as to why or when it happens.
The culprit is always the same and the stackdump also is always similar.  The big common factor seems to be the call to win.IsDialogMessage()  by  func (fb *FormBase) Run() int {...}
See line 432 of  \github.com\lxn\walk\form.go

			if !win.IsDialogMessage(fb.hWnd, &msg) {
				win.TranslateMessage(&msg)
				win.DispatchMessage(&msg)
			}

	github.com/lxn/win.IsDialogMessage(0xd0b9c, 0xc0029c0f20, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/win/user32.go:2387 +0x69
	github.com/lxn/walk.(*FormBase).Run(0xc000043c00, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/form.go:432 +0x42e
	main.RunMainWindow(0x0, 0x0)
		c:/Build/Accounting/Main.go:304 +0x3a21
	main.main()
		c:/Build/Accounting/Main.go:51 +0x42

**Comment by StephanVerbeeck** [comment]
Components that  I use are webview + win + walk functions (no external DLL's of my own that could cause memory damage)

**Comment by lxn** [comment]
Yeah, I'm getting those crashes in my apps as well. I have no idea what causes this. The crashes do not originate from `WebView`, as I also get them in apps not containing that widget.

I was recently invited to help with the walk based GUI for the Windows port of a cool open source project. The lead developer is pretty familiar with the Go runtime. If we'll observe the same problem there, and I may already have noticed it once, there is a lot of incentive to fix it.

**Comment by StephanVerbeeck** [comment]
Well I face 2 problems rather than one here.
1) that it crashes
2) it seems to be some kind of innocent null pointer problem that I would hide (when using C++) by a simple try-catch.  But as far as I know GOlang does not have an equivalent for that.

**Comment by kjk** [comment]
In my experience, the most common reason for crashes below `IsDialogMessage()` is doing GUI calls (basically calling things in `walk` or win calls that operate on `HWND`) without `Synchronize()`.

They are annoying as seemingly impossible to catch in the debugger.

Audit your code to see if you have any code where you run a goroutine and call GUI functions.

If your crash callstack shows all goroutines, see if the one that crashes is the main UI thread (i.e. first goroutine).

Suggestion for walk: a message loop could probably have a check and produce a clear warning to the programmer. Remember thread id of main thread on startup and compare with current thread id somewhere in `Run()` loop, panic with meaningful error message.

I'm not sure if that makes a difference or not, but try adding `runtime.LockOSThread()` to `func main()`.

**Comment by lxn** [comment]
@StephanVerbeeck You may want to try adding [recover](https://golang.org/ref/spec#Handling_panics) to the method containing the message loop. Haven't even tried that myself. I would imagine to then see some slowdown though. Memory may be corrupted anyway.

@kjk Is there a difference in adding `runtime.LockOSThread` to `func main` instead of having it called from a `func init` in a library package as done in lxn/win? Just asking because the lead dev on the project I mentioned recently replaced the call in a vendored copy of package win with one in `func main`.

**Comment by kjk** [comment]
@lxn didn't realize walk already calls `runtime.LockOSThread`. It should be equivalent to calling it in `main()`.

Honestly, I'm not sure if it's needed at all, this was "if all else fails, try that" suggestion. We're talking about main goroutine which should be locked to main thread anyway.

Is the open source project you mentioned that crashes publicly available? I might help tracking down the crash.

I was thinking walk could try to detect cases of calling GUI code from non-gui threads:
* remember main thread id in `init()`
* write `assertGUIThread()` function that compares that thread id with current thread id and panics with an informative error message
* sprinkle `assertGUIThread` throughout `walk`

Unfortunately, there's no way to audit all possible entry points, but some is probably better that nothing.

It could especially by added to frequently used functionality like `SendMessage` to cover most code paths.

It could also be publicly exposed as `AssertGUIThread` so that people could add those checks to their code.

**Comment by StephanVerbeeck** [comment]
I do have a go routine doing some message logic.
Going to try to convert it to a windows timer message.
The automatic runtime.LockOSThread() is also only called for the main thread ( see init() of lnx.win ) so I added it also to the go routine.
It will take a few days before I'm sure it has helped (I don't have a scenario yet that always provokes the error, but it does only occur while interacting with the program (mouse clicks))

**Comment by kjk** [comment]
@StephanVerbeeck no need to complicate with timers. Wrap all the code inside `Synchronize` call.
See https://www.programming-books.io/essential/go/a-first-window-app-e87631a7f8a94e8f92f9114e8e6baf0a#4 for explanation.

See https://github.com/essentialbooks/code/blob/master/go/windows/file_manager.go#L97 for a concrete example.

`Synchronize` is present on every `Widget`, including main window. It doesn't matter which widget you synchronize on (they all synchronize to main thread).

**Comment by StephanVerbeeck** [comment]
ok that could have been it.
I have found 6 locations where walk/win calls were made from inside a go routine and I have added widget.Synchronize() to all of them.
I remember having to apply the same logic from C++ and C# (keep forgetting that even GO still has to follow the old rules)

**Comment by StephanVerbeeck** [comment]
hmmm spoken to soon

	 Exception 0xc0000005 0x1 0xc0001d0f30 0x7ffdc1bf672e
	PC=0x7ffdc1bf672e

	syscall.Syscall(0x7ffdc1bf9440, 0x2, 0xb09d0, 0xc0001d0f20, 0x0, 0x0,
	0x0, 0x0)
		C:/build/Go/src/runtime/syscall_windows.go:186 +0xba
	github.com/lxn/win.IsDialogMessage(0xb09d0, 0xc0001d0f20, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/win/user32.go:2387 +0x69
	github.com/lxn/walk.(*FormBase).Run(0xc0003d5180, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/form.go:432 +0x42e
	main.RunMainWindow(0x0, 0x0)
		c:/Build/Accounting/Main.go:308 +0x3a26
	main.main()
		c:/Build/Accounting/Main.go:52 +0x42

	goroutine 12 [sleep]:
	time.Sleep(0x77359400)
		C:/build/Go/src/runtime/time.go:105 +0x12f
	main.CloseEmptyViewTabs()
		c:/Build/Accounting/ViewTabs.go:102 +0x15c
	created by main.StartInViewTab
		c:/Build/Accounting/ViewTabs.go:82 +0x87d
	rax     0x0
	rbx     0x2e11040
	rcx     0x1e1040
	rdi     0x0
	rsi     0xc0001d0f20
	rbp     0x2
	rsp     0xf9fd40
	r8      0xf9fc30
	r9      0x20
	r10     0x14
	r11     0xf9fb80
	r12     0x13
	r13     0x7ffda8b3d760
	r14     0x1
	r15     0x0
	rip     0x7ffdc1bf672e
	rflags  0x10246
	cs      0x33
	fs      0x53
	gs      0x2b

**Comment by lxn** [comment]
@kjk The project is available, but I'm not sure it really crashed the same way on me. It's a bit rough to get running, as you need to install a wip device driver, run Windows in test mode and be logged in as member of the Administrators group. I'm not in the office today, where I got a .msi for the driver, nor do I remember the URL of the unadvertised download.

Anyway, here's a mirror of the repo: https://github.com/WireGuard/wireguard-windows
And there's the driver repo: https://git.zx2c4.com/wintun/about/

@StephanVerbeeck Would have been nice if using `Synchronize` would have fixed it. IIRC some of my apps don't use concurrency at all, at least not in my code, and still manage to crash this way.

Have you tried the `recover` thing?

**Comment by kjk** [comment]
@lxn It does look like there's at least one unsynchronized call: https://github.com/WireGuard/wireguard-windows/blob/master/ui/ui.go#L287

**Comment by kjk** [comment]
@StephanVerbeeck that last call stack does seem like an instance of such problem. The crash happened on the main thread and goroutine 12, which seems to not be the main thread, calls code `ViewTabs.go`. Is the code there manipulates widgets?

**Comment by StephanVerbeeck** [comment]
No, (I already isolated all this logic in Synchronize() calls) the go routine there is sleeping (there is a separate stackdump per thread).
It also occurred before any of the go routines were added.

**Comment by lxn** [comment]
@kjk Thanks for having a look. Yeah, I noticed that one yesterday, too. Just really started working on the project this week and didn't pay much attention to this so far. Most recent branch is `an/gui`, but it's the same problem there. I'd also imagine the callback registered by `service.IPCClientRegisterTunnelChange` to arrive on a different goroutine. Will have to look into all that soon.

Maybe I should try to build a simple repro app when I get some time.

**Comment by zx2c4** [comment]
![image](https://user-images.githubusercontent.com/10643/56848574-0612a800-68eb-11e9-8122-07cd15387bf9.png)
I'm actually able to repro with the debugger attached.
