### ISSUE TITLE
Embedding walk.Image in code

### ISSUE THREAD

**Issue by ogau** [lxn/walk#484]
I have a set of more than a hundred images on the hard drive that I have to use in the application. I need maximum performance and therefore I decided to embed them in the code.

let's say I have an *image.RGBA (2x1) type embedded in the code variable
```
src = &image.RGBA{
	Pix:    []uint8{0x0, 0x0, 0x0, 0xff, 0x0, 0xa2, 0xe8, 0xff},
	Stride: 8,
	Rect:   image.Rectangle{Min: image.Point{X: 0, Y: 0}, Max: image.Point{X: 2, Y: 1}},
}
```
but I want to do without calling the `walk.NewBitmapFromImage(src)` function, and embed the result of calling this function in the code.
How to do this?

**Comment by lxn** [comment]
You can't. At least I don't know how, sorry.
