### ISSUE TITLE
How to insert TableViewColumn in Table?

### ISSUE THREAD

**Issue by ogau** [lxn/walk#488]
Code below does not work.
One more question: Is there a better way to define multiple homogeneous columns? For example, I have them 117
```
OnClicked: func() {
	for x := range model.items {
		model.items[x].E2 = rand.Intn(50)
	}
	col := walk.NewTableViewColumn()
	col.SetName("E2")
	col.SetTitle(rndname())
	tv.Columns().Insert(2, col)
}
```

![изображение](https://user-images.githubusercontent.com/25056868/56308344-8bb28d00-6160-11e9-94c4-34b7ed66958e.png)

```
package main

import (
	"math/rand"
	"time"

	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

type FooModel struct {
	walk.SortedReflectTableModelBase
	items []*Foo
}

func (m *FooModel) Items() interface{} {
	return m.items
}

type Foo struct {
	E0, E1, E2, E3, E4 int
}

func NewFooModel() *FooModel {
	rand.Seed(time.Now().UnixNano())

	m := new(FooModel)
	m.items = make([]*Foo, 10)
	for i := range m.items {
		m.items[i] = &Foo{
			E0: rand.Intn(50),
			E1: rand.Intn(50),
			// E2: rand.Intn(50), pass
			E3: rand.Intn(50),
			E4: rand.Intn(50),
		}
	}
	m.PublishRowsReset()
	return m
}

var names = []string{
	"Oliver", "Amelia", "Jack", "Harry", "Jacob",
	"Isla", "Emily", "Ava", "Mia", "Sophia",
	"Charlie", "Freddie", "Oscar", "Grace", "Isabella",
	"George", "Noah", "Alfie", "Lily", "Olivia",
}

func rndname() string {
	return names[rand.Intn(len(names))]
}

func main() {
	model := NewFooModel()
	var tv *walk.TableView
	var mw *walk.MainWindow

	MainWindow{
		AssignTo: &mw,
		Size:     Size{500, 200},
		Layout:   VBox{},
		Children: []Widget{
			PushButton{
				Text: "Insert E2 column and fill in data",
				OnClicked: func() {
					for x := range model.items {
						model.items[x].E2 = rand.Intn(50)
					}
					col := walk.NewTableViewColumn()
					col.SetName("E2")
					col.SetTitle(rndname())
					tv.Columns().Insert(2, col)
				},
			},
			TableView{
				AssignTo: &tv,
				Columns: []TableViewColumn{
					{Name: "E0", Title: rndname()},
					{Name: "E1", Title: rndname()},
					// {Name: "E2", Title: rndname()}, pass
					{Name: "E3", Title: rndname()},
					{Name: "E4", Title: rndname()},
				},
				Model: model,
			},
		},
	}.Run()
}

```

**Comment by StephanVerbeeck** [comment]
This question has already been answered here: https://github.com/lxn/walk/issues/408
Here is some example code (part of an application that alters table view layout based on external settings

	// SetViewHistoryColumns set the column titles of the historyTableView (adding or removing columns when needed)
	func SetViewHistoryColumns(colIDs []string) {
		historyTableView.SetVisible(true)
		comPeriod.Layout().Update(true)

		if historyViewRedraw { // don't skip changing layout of columns (even when periods in history are the same)
			historyViewRedraw = false
		} else if JoinLines(historyPeriodIDs...) == JoinLines(colIDs...) {
			return // columns already have the right count and titles
		}
		historyPeriodIDs = colIDs

		historyTableView.SetSuspended(true)
		defer historyTableView.SetSuspended(false)
		historyTableView.Columns().Clear()

		// add column for post ID
		col := walk.NewTableViewColumn()
		col.SetFrozen(len(colIDs) > 1)
		col.SetWidth(50)
		col.SetTitle("ID")
		col.SetName("ID")
		historyTableView.Columns().Add(col)

		// add column for post Title
		col = walk.NewTableViewColumn()
		col.SetFrozen(len(colIDs) > 1)
		col.SetWidth(150)
		col.SetTitle("Title")
		col.SetName("Title")
		historyTableView.Columns().Add(col)

		// add column(s) per period
		addCol := func(title string) {
			col := walk.NewTableViewColumn()
			col.SetTitle(title)
			col.SetAlignment(walk.AlignFar)
			col.SetFormat("%.2d")
			col.SetWidth(100)
			historyTableView.Columns().Add(col)
		}

		for _, periodID := range historyPeriodIDs {
			switch accountingSettings.HistoryViewMethod {
			case HVM_Debet:
				addCol(JoinWords(periodID, "Debet"))
			case HVM_Credit:
				addCol(JoinWords(periodID, "Credit"))
			case HVM_Start:
				addCol(JoinWords(periodID, "Start"))
			case HVM_End:
				addCol(JoinWords(periodID, "End"))
			case HVM_Diff:
				addCol(JoinWords(periodID, "Diff"))
			case HVM_SinglePeriod:
				fallthrough
			case HVM_All:
				addCol(JoinWords(periodID, "Debet"))
				addCol(JoinWords(periodID, "Credit"))
				addCol(JoinWords(periodID, "Start"))
				addCol(JoinWords(periodID, "End"))
				addCol(JoinWords(periodID, "Diff"))
			default:
				addCol(JoinWords(periodID, "Debet"))
			}
		}

		historyTableModel.PublishRowsReset()
	}

**Comment by ogau** [comment]
If I add a column to an empty table model, I get an index error. Do I need to initially initialize the required number of columns?
Example: 
```
TableView{
	AssignTo: &tv,
	Columns: []TableViewColumn{},
	Model: model,
},
```
