### ISSUE TITLE
window freez when exec cmd

### ISSUE THREAD

**Issue by srijib** [lxn/walk#490]
I have a simple window with few buttons. each suppose to open some other application. 
when i open iexplore the window freezes. In android application we have async task that runs background task in a seperate thread. any option to achieve it here ?
Eg:
`PushButton{
				Text: "Launch Notepad",
				OnClicked: func() {
					cmd := exec.Command("notepad.exe")
						if err := cmd.Run(); err != nil{
						   fmt.Println(err)
						}
				},
			},`

**Comment by kjk** [comment]
`Cmd.Run` is blocking. Either run `Cmd.Start` or run this in a gorutine.
