### ISSUE TITLE
Icons on TableView headers

### ISSUE THREAD

**Issue by ogau** [lxn/walk#496]
How can this be done?
How can set a font for headers?

**Comment by lxn** [comment]
This is untested and incomplete, but should get you going:

```Go
...
TableView{
	StyleCell: func(style *walk.CellStyle) {
		if style.Row() == -1 { // Header
			if canvas := style.Canvas(); canvas != nil {
				// Draw using the canvas inside style.Bounds()
			}
		}
	}
},
...
```

**Comment by ogau** [comment]
unfortunately the condition `if style.Row() == -1` is not satisfied, I checked it with console output using `fmt.Println(1)` inside.

**Comment by lxn** [comment]
Hmm, please try if adding `CustomHeaderHeight: someHeight,` to your `TableView` helps.

**Comment by ogau** [comment]
Great, it helped! Thank you for your product.
