### ISSUE TITLE
same problem solved twice?

### ISSUE THREAD

**Issue by zx2c4** [lxn/walk#505]
8bf51810 tried to fix the weird partially selected/scrolled code in one way. That didn't work, and so 431cd50e got bolted ontop to try again another way. That evidently doesn't work either.

![image](https://user-images.githubusercontent.com/10643/57194436-473c3500-6f47-11e9-80b1-027cf34aaba5.png)

What's up? Decide on one way of doing this perhaps?

We're working around this now with https://git.zx2c4.com/wireguard-windows/commit/?id=9adeb2762644fd91c6321dcc7d1a33e56c50a616

**Comment by lxn** [comment]
This should be fixed by https://github.com/lxn/walk/commit/bf6b8a4b207d83866fe5cef6ad09cd4fccc6d65c
