### ISSUE TITLE
dos not work on windows xp sp3

### ISSUE THREAD

**Issue by dragonvc** [lxn/walk#524]
i try use the example.
but the Program Crashes.

i use import _ "runtime/cgo" or "-linkmode internal".
but no work.

environment:
build:

go 1.11.6 amd64

set CGO_ENABLED=1
set CC=gcc
set GOARCH=386
go build

D:\>test700.exe
panic: CreateWindowEx

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x0, 0x865220, 0x4c558f)
        C:/Go/src/runtime/debug/stack.go:24 +0x8a
github.com/lxn/walk.newErr(0x650509, 0xe, 0x11469e10, 0x0)
        D:/workspace/go/src/github.com/lxn/walk/error.go:81 +0x1e
github.com/lxn/walk.newError(0x650509, 0xe, 0x80000000, 0x80000000)
        D:/workspace/go/src/github.com/lxn/walk/error.go:85 +0x29
github.com/lxn/walk.lastError(0x650509, 0xe, 0x0, 0x8c000001)
        D:/workspace/go/src/github.com/lxn/walk/error.go:97 +0x113
github.com/lxn/walk.InitWindow(0x687100, 0x11498000, 0x0, 0x0, 0x6516ca, 0x10, 0
x88000001, 0x0, 0x0, 0x0)
        D:/workspace/go/src/github.com/lxn/walk/window.go:527 +0x9d1
github.com/lxn/walk.newToolTip(0x0, 0x0, 0x0, 0x0)
        D:/workspace/go/src/github.com/lxn/walk/tooltip.go:50 +0x8d
github.com/lxn/walk.NewToolTip(0x5746db, 0x656137, 0x1c)
        D:/workspace/go/src/github.com/lxn/walk/tooltip.go:37 +0x25
github.com/lxn/walk.init.20()
        D:/workspace/go/src/github.com/lxn/walk/tooltip.go:25 +0x1a

goroutine 1 [running]:
github.com/lxn/walk.init.20()
        D:/workspace/go/src/github.com/lxn/walk/tooltip.go:26 +0x5f

i try to debug:
i found CreateWindowEx use a className call tooltips_class32, and lastError return 1411(class does not exists)....

thanks...

**Comment by Sunzhuokai** [comment]
how to fix？
