### ISSUE TITLE
Window initialization sometimes hangs up

### ISSUE THREAD

**Issue by fpawel** [lxn/walk#546]
After several last patches, nondeterministic hangs appeared during initialization of the main window and dialogs. For example, here is the result of normal loading:
![picture](https://user-images.githubusercontent.com/6129096/58468365-174b1080-8146-11e9-8388-82ae7da86fd2.png)
And here is the result of a hangup that occurs approximately once in ten launches of the application.
![изображение](https://user-images.githubusercontent.com/6129096/58468529-6002c980-8146-11e9-8e83-b08793956394.png)

**Comment by fpawel** [comment]
Here is a minimal example to reproduce the bug. It hangs on `c.SetVisible(false)` line.
```
import (
	"fmt"
	"github.com/lxn/walk"
	. "github.com/lxn/walk/declarative"
)

func main() {

	var (
		c *walk.Composite
		w *walk.MainWindow
		)
	err := (MainWindow{
		AssignTo:&w,
		Layout: VBox{},
		Children: []Widget{
			Composite{
				AssignTo:&c,
				Layout: HBox{},
			},
		},
	}).Create()
	fmt.Println("created")
	if err!=nil{
		panic(err)
	}
	c.SetVisible(false)
	fmt.Println("run")
	w.Run()
	fmt.Println("exit")
}
```

**Comment by lxn** [comment]
Please try if this is fixed by https://github.com/lxn/walk/commit/5565977633e7513a91eea1bbb7d098f46f5c0ac0.

**Comment by fpawel** [comment]
@lxn yes, it fixed the error. The problem was with `ScrollView`-s with `Layout: VBox{},	HorizontalFixed:true,` or `Layout: HBox{}, VerticalFixed:true,` (to emulate the behaviour of `StackPanle` from WPF). Now it works fine.
