### ISSUE TITLE
[BUG] walk.Splitter stops when the control is generated.

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#548]
![image](https://user-images.githubusercontent.com/16282726/58691133-baf22600-83bd-11e9-9351-5d9df8d91d0a.png)

Sometimes it loads successfully, it all loads quickly, and sometimes it becomes like this.

**Comment by HeyDon-Lee** [comment]
@lxn

**Comment by HeyDon-Lee** [comment]
There are no error hints.
I tried to print the error message.

**Comment by HeyDon-Lee** [comment]
@StephanVerbeeck
Can you see what the problem is?

**Comment by lxn** [comment]
Please try if this is fixed by https://github.com/lxn/walk/commit/5565977633e7513a91eea1bbb7d098f46f5c0ac0.

**Comment by HeyDon-Lee** [comment]
@lxn Problem solved. Thank you.
