### ISSUE TITLE
Is there any way to raise the maximum word limit for walk.NewTextEdit?

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#556]
Is there any way, like notepad, not to limit the number of words?

**Comment by HeyDon-Lee** [comment]
@lxn

**Comment by lxn** [comment]
You can call `yourTextEdit.SetMaxLength(newMaxLength)` to change the maximum text length or set the corresponding `MaxLength` field in the declarative struct.

**Comment by HeyDon-Lee** [comment]
TextEdit.SetMaxLength (INT_MAX) is still limited to 1615 words. 
Is it because the scroll bar is not turned on? 
So how do I open the scroll bar for TextEdit?

**Comment by lxn** [comment]
If the issue is the missing scroll bar, you can do the same as the declarative package:
https://github.com/lxn/walk/blob/master/declarative/textedit.go#L63-L74

If it doesn't help, maybe try lower values than INT_MAX.

**Comment by HeyDon-Lee** [comment]
Thank you. After adding a scroll bar, you don't have to set the maximum number of words.
