### ISSUE TITLE
RadioButtonGroup 如何默认选中其中一个 RadioButton

### ISSUE THREAD

**Issue by ZongzhiCui** [lxn/walk#558]
如题!

**Comment by lxn** [comment]
Just set the value of the initially to be selected `RadioButton` in the data source field specified by `DataMember`.

**Comment by ZongzhiCui** [comment]
`                                                                      RadioButtonGroup{

										DataMember: "cRB",
										Buttons: []RadioButton{
											RadioButton{
												AssignTo: &mw.radioBtn1_1,
												Name:     "aRB",
												Text:     "不变",
												Value:    "1",
												MaxSize: Size{Width:50},
												ToolTipText: "矿工名后缀",
											},
											RadioButton{
												AssignTo: &mw.radioBtn1_2,
												Name:     "bRB",
												Text:     "无",
												Value:    "2",
												MaxSize: Size{Width:50},
												ToolTipText: "矿工名后缀",
											},
											RadioButton{
												AssignTo: &mw.radioBtn1_3,
												Name:     "cRB",
												Text:     "IP",
												Value:    "3",
												MaxSize: Size{Width:50},
												ToolTipText: "矿工名后缀",
											},
										},

									},`
我想要选中第三个 RadioButton, 可是尝试了DataMember: "cRB"和DataMember: "3", 都不能成功

**Comment by lxn** [comment]
Try to do it like this:

```Go
...
type MyDataSource struct {
	Food string
...
}

// Set Food to the value of the desired initial option before assigning myDataSource to the DataBinder.
myDataSource := MyDataSource{Food: "meat"}
...
RadioButtonGroupBox{
	Title:      "Food",
	Layout:     HBox{},
	DataMember: "Food",
	Buttons: []RadioButton{
		{Text: "Eggs", Value: "eggs"},
		{Text: "Meat", Value: "meat"},
		{Text: "Cheese", Value: "cheese"},
	},
},
...
```

**Comment by ZongzhiCui** [comment]
感谢作者的您的耐心回复,我会再次尝试!!

**Comment by thomasbrook** [comment]
value

**Comment by ZongzhiCui** [comment]
.rsrc merge failure:报错. 处理方法: go build -ldflags="-H windowsgui -linkmode internal"

**Comment by dzcpy** [comment]
I would suggest you to use English to raise issues since apparently the author 不说中文
