### ISSUE TITLE
PushButton walk.EventHandler里做HTTP请求的时候,桌面应用就会强制退出

### ISSUE THREAD

**Issue by ZongzhiCui** [lxn/walk#559]
如题,
`	ipServReq := "http://" + ipServ
	resp, _ := curl.HPost(ipServReq)
	//resp, _ := curl.HPost(ipServ)

	var oreInfo interface{}
	err := json.Unmarshal([]byte(resp), &oreInfo)
	if err != nil {
		errInfo = err.Error()
		status = 0
	}`
以上代码导致程序退出.
![1560418339(1)](https://user-images.githubusercontent.com/36881440/59421512-4c6f8800-8e01-11e9-84e7-b2f19bc543e9.jpg)

**Comment by lxn** [comment]
No idea what's going on here. Just a guess, but if you try to call any walk function or method of a walk widget from another goroutine, you need to do it like this:

```Go
...
var myTextEdit *walk.TextEdit
...
go func() {
...
	myTextEdit.Synchronize(func() {
		myTextEdit.SetText("hello")
	})
...
}()
...
```

**Comment by ZongzhiCui** [comment]
一语中的~您讲到了要点,正是我遇到的问题~~再次感谢
