### ISSUE TITLE
A suggestion about code hints. 

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#561]
Fill in the code comment on the func. 
There are hints when writing in Visual Studio Code. 

![](https://user-images.githubusercontent.com/16282726/59445576-7f7e3f80-8e32-11e9-800a-a2612ce73d98.png)

![](https://user-images.githubusercontent.com/16282726/59445536-6d9c9c80-8e32-11e9-9304-db1b7c5c4aa1.png)

**Comment by lxn** [comment]
Sorry, I know many exported items lack docs, but quite often those add not much value beyond what the item name reveals anyway.
