### ISSUE TITLE
How do I delete a child control of a control?

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#565]
I used a Composite to box some controls. 
Clearing some of these controls when you click some buttons produces some new controls.

**Comment by lxn** [comment]
Looks like [this](https://github.com/lxn/walk/issues/435#issuecomment-445177646) is still not fixed.

**Comment by HeyDon-Lee** [comment]
Thank you

```go
control.SetParent(nil)
control.Dispose()
```
