### ISSUE TITLE
How to bind the event?

### ISSUE THREAD

**Issue by evidwong** [lxn/walk#572]
Hi!
How to bind the event when I use the UI from ui2walk?
For the button,how can i bind the clicked event?

**Comment by lxn** [comment]
Hey!
Is ui2walk working for you? It hasn't been maintained for a long time.

You can do it like this:
```Go
myButton.Clicked().Attach(func() {
    // Handle clicked event here
})
```

**Comment by evidwong** [comment]
yeah! I have try it and success, thanks.
