### ISSUE TITLE
关闭桌面应用后,再次开启如何记录上次文本框输入的值

### ISSUE THREAD

**Issue by ZongzhiCui** [lxn/walk#573]
![1](https://user-images.githubusercontent.com/36881440/59912495-bcf15700-9448-11e9-9676-df21fa3537ea.png)
![2](https://user-images.githubusercontent.com/36881440/59912516-c5e22880-9448-11e9-8759-fa4755bb6949.png)
![3](https://user-images.githubusercontent.com/36881440/59912523-c975af80-9448-11e9-8dfc-0c18a8b8591f.png)
最后再次打开桌面应用的时候,我希望文本框显示的是上次输入的值!如何操作?

**Comment by lxn** [comment]
Please have a look at the `settings` example. You will have to use the `Get` and `Put` methods of `IniFileSettings`.

**Comment by ZongzhiCui** [comment]
感谢!感谢!已经越来越感受到 lxn/walk 功能的强大
