### ISSUE TITLE
TableView 有没有可编辑 的示例

### ISSUE THREAD

**Issue by ZongzhiCui** [lxn/walk#586]
![image](https://user-images.githubusercontent.com/36881440/61360354-de5f2a80-a8b0-11e9-8102-fc7162d550f7.png)
点击IP段 两次,就是可编辑状态!  有没有类似功能的 示例?

**Comment by lxn** [comment]
That's not supported, sorry!

You would have to implement editing like it is done in the databinding example. I do the same in all my apps and have no plans to add editing to `TableView`.
