### ISSUE TITLE
my go version is 1.12,when i am using walk ,get something wrong!

### ISSUE THREAD

**Issue by GuiLongLi** [lxn/walk#587]
---------------------------------------------------------------
[root@localhost aichatwindow]# cat go.mod
module aichatwindow

go 1.12

require (
	github.com/gin-gonic/gin v1.4.0
	github.com/lxn/walk v0.0.0-20190619151032-86d8802c197a
	github.com/lxn/win v0.0.0-20190716185335-d1d36f0e4f48 // indirect
	github.com/spf13/viper v1.4.0
	github.com/tidwall/gjson v1.3.2
	gopkg.in/Knetic/govaluate.v3 v3.0.0 // indirect
)

replace github.com/lxn/walk v0.0.0-20190619151032-86d8802c197a => ./vendor/github.com/lxn/walk
-------------------------------------------------------------------
[root@localhost aichatwindow]# go build
go: parsing vendor/github.com/lxn/walk/go.mod: open /usr/local/go/study/aichatwindow/vendor/github.com/lxn/walk/go.mod: no such file or directory

**Comment by GuiLongLi** [comment]
how do i fix it??

**Comment by kjk** [comment]
walk doesn't have `go.mod` file (yet?) so it's not a module so you can't use `replace`. `replace` works on modules and lxn\walk is not a module because it doesn't have `go.mod`.

That's what the error message says.

In general using vendor directories in the world of modules doesn't make much sense. You can pin exact version of `lxn/walk` in your `go.mod` file.

**Comment by GuiLongLi** [comment]
yet ,i remove the replace from go.mod file
but there is get another wrong 
------------------------------------------------------------------
[root@localhost aichatwindow]# cat go.mod
module aichatwindow

go 1.12

require (
	github.com/gin-gonic/gin v1.4.0
	github.com/lxn/walk v0.0.0-20190619151032-86d8802c197a
	github.com/lxn/win v0.0.0-20190716185335-d1d36f0e4f48 // indirect
	github.com/spf13/viper v1.4.0
	github.com/tidwall/gjson v1.3.2
	gopkg.in/Knetic/govaluate.v3 v3.0.0 // indirect
)
[root@localhost aichatwindow]# go build
build aichatwindow: cannot load github.com/lxn/walk: no Go source files

**Comment by GuiLongLi** [comment]
i have go get github.com/lxn/walk

----------------------------------------------------------
[root@localhost aichatwindow]# go get github.com/lxn/walk
go: finding github.com/lxn/walk latest
package github.com/lxn/walk: build constraints exclude all Go files in /root/go/pkg/mod/github.com/lxn/walk@v0.0.0-20190619151032-86d8802c197a
[root@localhost aichatwindow]# go build
build aichatwindow: cannot load github.com/lxn/walk: no Go source files

**Comment by kjk** [comment]
There's no `go.mod` in `lxn\win` therefore `lxn\win` is not a module, therefore you can't use `replace` in your `go.mod`.

Also, you're compiling on linux and `lxn\win` is for windows applications only. You can cross-compile on linux if you set `GOOS`env variable to `windows`.

**Comment by GuiLongLi** [comment]
ok, now i add GOOS=windows , so what it is going on

-------------------------------------------------------

[root@localhost aichatwindow]# CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build
# github.com/lxn/walk
/root/go/pkg/mod/github.com/lxn/walk@v0.0.0-20190619151032-86d8802c197a/icon.go:121:19: undefined: "golang.org/x/sys/windows".GetSystemDirectory

**Comment by GuiLongLi** [comment]
it works , thanks a lot

at last when i get golang.org/x/crypto,it is works
[root@localhost aichatwindow]# go get -u -v golang.org/x/crypto/...
