### ISSUE TITLE
Go 1.13

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#603]
![image](https://user-images.githubusercontent.com/16282726/64250009-9c18a800-cf47-11e9-8c73-d84316c555a5.png)

**Comment by HeyDon-Lee** [comment]
@lxn Three warnings were prompted after Golang upgrade 1.13, but the compiled program was not affected.

**Comment by lxn** [comment]
Thanks for reporting, but all of these seem to be false positives.
