### ISSUE TITLE
ToolBarButtonTextOnly doesn't work 

### ISSUE THREAD

**Issue by jackyzy823** [lxn/walk#613]
After some git-bisect, i found that after commit 396216245a30b92853eb935b6caf15f5a6f82f9e ,ToolBarButtonTextOnly  doesn't work.

If i  change `declarative/toolbar.go` only  to previous commit. ToolBarButtonTextOnly  works properly.

These are the codes deleted in https://github.com/lxn/walk/commit/396216245a30b92853eb935b6caf15f5a6f82f9e#diff-ee6a50074bd18cd538fb2031874fbe21 :
```go
		imageList, err := walk.NewImageList(walk.Size{16, 16}, 0)
		if err != nil {
			return err
		}
		w.SetImageList(imageList)
```

So how to make ToolBarButtonTextOnly  work properly. To add back this code , or to do some  other changes?

Thanks.

**Comment by lxn** [comment]
Thanks for reporting! It has been added back in https://github.com/lxn/walk/commit/1eeae07769d2bcd472083994a0a974f635c017ba.
