### ISSUE TITLE
Crash encountered when calling NewMainWindow

### ISSUE THREAD

**Issue by ladevieq** [lxn/walk#632]
Hi,

First of all, thanks for the great work on walk.

Since i uptaded walk to a recent version (the previous version was 8 month old), calling `NewMainWindow()` make the program crash.

I'm using Windows10 and Go 1.13.

The crash logs the message `TTM_ADDTOOL failed`.

The problem happen when the code try to add a tooltip, in `tooltip.go`, line 185.

After some investigation, i'm not sure about it but, i found that the value returned by the function is not the same as `win.FALSE` but the error is thrown anyway.

**Comment by lxn** [comment]
Hey,

Thanks for the kind words.

Your previous version of walk probably generated a manifest file for you. In https://github.com/lxn/walk/pull/451/commits/a66955062fa637aa4bcae7707dbc51e1d1c1254f this behavior was reverted. Please have a look at the `README` file for what to do.

**Comment by ladevieq** [comment]
Hey,

I've started using a manifest as in the examples, and it works perfectly.

Thank you keep on the great work.

👍
