### ISSUE TITLE
TextEdit with CompactHeight becomes very thin

### ISSUE THREAD

**Issue by harry1453** [lxn/walk#644]
```go
Label{
    Text: "Input File:",
},
TextEdit{
    AssignTo: &inFile,
    CompactHeight: true,
},
```
Results in (when the `TextEdit` is empty)
![image](https://user-images.githubusercontent.com/37041552/67967376-6a495800-fbfd-11e9-9bd6-42508651f8d4.png)

Typing in the box makes it go back to normal size.

![image](https://user-images.githubusercontent.com/37041552/67967549-b1374d80-fbfd-11e9-9207-f4c1bee3bb39.png)

Is the super thin TextEdit expected behaviour? I would expect it to have a constant height equivalent to its height when there is one line of text, otherwise it becomes difficult to select to enter text.

**Comment by lxn** [comment]
This should be fixed by https://github.com/lxn/walk/commit/7370661788f6e954d749d664908a26293a3d952d.

**Comment by harry1453** [comment]
It's fixed, thank you very much!
