### ISSUE TITLE
How do I use multithreading?

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#646]
window.Run() after the thread can not be used, how to solve?

**Comment by HeyDon-Lee** [comment]
@lxn

**Comment by lxn** [comment]
You could probably do it like [this](https://github.com/lxn/walk/issues/626#issuecomment-538062977).

**Comment by HeyDon-Lee** [comment]
@lxn Failed and the application did not respond directly. 
Is there any other way?
