### ISSUE TITLE
Is there a component with a built-in WindowsMediaPlayer in lxn/walk?

### ISSUE THREAD

**Issue by HeyDon-Lee** [lxn/walk#647]
I want to make a Gui program that plays music or video.

**Comment by HeyDon-Lee** [comment]
@lxn

**Comment by lxn** [comment]
No, there isn't.

**Comment by HeyDon-Lee** [comment]
Are you going to add this component?

**Comment by lxn** [comment]
It's probably quite some work and I have no use for it, so probably not, sorry.
