### ISSUE TITLE
undefined  win.HDHITTESTINFO   

### ISSUE THREAD

**Issue by senys** [lxn/walk#670]
I've get walk. And run some sampleCode.
So, following error occurred.

```
 [myroot]\go\pkg\mod\github.com\lxn\walk@v0.0.0-20191128110447-55ccb3a9f5c1\tableview.go:2449:10: undefined: win.HDHITTESTINFO
 ```

And , I cannot found   `win.HDHITTESTINFO` in srccode.

OS
windows10 64bit

**Comment by kjk** [comment]
You need to update lxn\win package e.g. with `go get -u github.com\lxn\win`

**Comment by senys** [comment]
Thanks!
It worked.

**Comment by kjk** [comment]
@lxn adding `go.mod` would fix issues like that
