### ISSUE TITLE
how to append text to textedit

### ISSUE THREAD

**Issue by Assassintears** [lxn/walk#680]
I code a tcp client  desktop app, want to receive string data from the server and put it to textedit. Now the error description likes bellow when I calling AppendText of textedit.

![image](https://user-images.githubusercontent.com/18465107/79682382-48e43300-8254-11ea-8061-caab20678893.png)

![image](https://user-images.githubusercontent.com/18465107/79682431-c7d96b80-8254-11ea-92dd-ed692cb76297.png)

![image](https://user-images.githubusercontent.com/18465107/79682444-f1929280-8254-11ea-8fe9-b90828837bdc.png)

**Comment by kjk** [comment]
The error tells you that `str` contains a byte 0 in it (which is not a valid character).
Most likely this happens because `Read()` doesn't fill the whole `by` and the rest of it is filled with default 0 bytes.
Try:
```
n, err := tcp.conn.Read(by)
...
tcp.Ch <- string(by[:n])
```

**Comment by Assassintears** [comment]
@kjk yes, I fixed the problem with your method, thank you very much
