### ISSUE TITLE
Will this library be developed and maintained?

### ISSUE THREAD

**Issue by fpawel** [lxn/walk#684]
Dear @lxn and other contributors, do you have any plans regarding walk?

**Comment by lxn** [comment]
Sorry for the prolonged radio silence, I'm pretty busy with other stuff since quite some time.

As I have to maintain some bigger walk based apps, the plan is to continue working on walk. Will probably be some more weeks before returning to it though.

**Comment by fpawel** [comment]
Thank you for clarifying. I think it is closed
