### ISSUE TITLE
No UpDown Control with NumberEdit

### ISSUE THREAD

**Issue by MaxBanister** [lxn/walk#688]
Hello, I'm new to the project but thank you for all the hard work you have put in.

One feature that I think would be nice to have is an UpDown companion control to the NumberEdit, like this:

![Screenshot from 2020-05-17 21-09-20](https://user-images.githubusercontent.com/32582595/82174666-39253200-9886-11ea-8241-d40a8a4e7b38.png)

Right now, I am emulating this feature by stacking two PushButtons in a GridLayout, which looks somewhat convincing, but getting the arrows to look native has proved a bit challenging:

![Screenshot from 2020-05-17 21-09-32](https://user-images.githubusercontent.com/32582595/82174705-5eb23b80-9886-11ea-96d3-c44bf6e00012.png)

I could use bitmaps or special fonts, but it would be nice to have this feature out of the box. If you have any suggestions on how to create this functionality, please let me know.

**Comment by lxn** [comment]
Initially `NumberEdit` used an `UpDown` control, but it just looked ugly on some Windows versions and seemed to be a waste of space, so it got removed. If you really need it, we may try to add it back as an option.

**Comment by lxn** [comment]
Implemented in https://github.com/lxn/walk/commit/f7621aeb8225ff560a1b58a5f461735b291f05f8.

**Comment by MaxBanister** [comment]
Hmm, I see what you mean by ugly. The new SpinButton seems to be too narrow (tested on Wine). Somehow though, other applications, like the example I gave above, seem to not suffer this issue (maybe because it's not a "buddy" component?). Do you know of any workarounds for this?

[
![Screenshot from 2020-09-04 17-41-42](https://user-images.githubusercontent.com/32582595/92293343-b2996c80-eed7-11ea-9ccd-757605bb6074.png)
](url)

Thanks for making this commit though, much appreciated.

**Comment by MaxBanister** [comment]
Update: looks fine on Windows 10

![numberedit](https://user-images.githubusercontent.com/32582595/92296974-3448c480-eeef-11ea-8ed3-03ad85b778d1.png)
