### ISSUE TITLE
Groupbox title support Chinese

### ISSUE THREAD

**Issue by winxxp** [lxn/walk#690]
![image](https://user-images.githubusercontent.com/4273458/83228352-c33f9580-a1b8-11ea-9471-a43d2b75cb90.png)

**Comment by danny50610** [comment]
The upper part of the title seems to be cut off

**Comment by winxxp** [comment]
```go
			offset := gb.headerHeight / 4
			wbcb := gb.WidgetBase.ClientBoundsPixels()
			if !win.MoveWindow(
				gb.hWndGroupBox,
				int32(wbcb.X),
				int32(wbcb.Y/*-offset*/),  // delete offset is ok
				int32(wbcb.Width),
				int32(wbcb.Height),
				true) {

				lastError("MoveWindow")
				break
			}
```

**Comment by lxn** [comment]
This should be fixed by https://github.com/lxn/walk/commit/97e648c9f710630ce59c4617693baf14dcc103c8.

Thanks for reporting and also coming up with the fix!
