### ISSUE TITLE
请问如何用walk实现一个小游戏

### ISSUE THREAD

**Issue by 15951836388** [lxn/walk#692]
我参考了范例里的draw，可以画出东西，但是
Paint:               mw.drawStuff,  
这个方法似乎只调用了一次。怎么手动调用重新绘制的方法？
要实现游戏，需要把变化的数据，不停的循环画出来。
这些数据，可能是其他携程传递过来的。
希望可以有个类似游戏的范例

**Comment by winxxp** [comment]
Invalidate试试

**Comment by StephanVerbeeck** [comment]
To provoke a redraw you need indeed to invalidate the window.
see windows documentation for this (this is not GOlang/walk specific).
https://docs.microsoft.com/en-us/windows/win32/gdi/wm-paint
