### ISSUE TITLE
Anti aliasing api support

### ISSUE THREAD

**Issue by tky753** [lxn/walk#709]
I use `CustomWidget` to draw step widget like this:
![image](https://user-images.githubusercontent.com/18205977/90495142-d8eca780-e176-11ea-877a-3502492b824e.png)
Is there a way for **Anti-aliasing**

**Comment by lxn** [comment]
Walk currently uses [GDI](https://docs.microsoft.com/en-us/windows/win32/gdi/windows-gdi), which does not support it. I would like to use [Direct2D](https://docs.microsoft.com/en-us/windows/win32/direct2d/direct2d-portal) instead, but that would be a lot of work.

Maybe you could accomplish your task with some Go package like https://github.com/fogleman/gg. When I implemented graphics effects for walk, I first used that package. Sadly it was too slow for that feature to work properly, but it may work well for your use case. `walk.Bitmap` has some standard Go `image.Image` interop stuff to integrate this.

**Comment by tky753** [comment]
What about GDI+

**Comment by lxn** [comment]
You are right, it could make sense to use GDI+ selectively for some features, at least in the shorter term. It's already used to load images after all. Needs some investigation, but I'm afraid I can't invest a lot of time into this right now.
