### ISSUE TITLE
walk no longer builds

### ISSUE THREAD

**Issue by cryptonote-social** [lxn/walk#716]
Seems may be related to the most recent commit?

\walk>go get -u
# github.com/lxn/walk
.\mainwindow.go:48:12: undefined: initWindowWithCfg
.\mainwindow.go:48:31: undefined: windowCfg

**Comment by jackyshaw2017** [comment]
the same error

**Comment by cryptonote-social** [comment]
looks like an incomplete checkin from the last commit....  some updates to window.go are missing.

**Comment by lxn** [comment]
Sorry guys, will fix tomorrow when in the office.

**Comment by lxn** [comment]
It's fixed.

**Comment by cryptonote-social** [comment]
yep works for me, thank you!
