### ISSUE TITLE
ComboBox doesn't trigger `OnCurrentIndexChanged` handler, when receiving: `win.CBN_SELCHANGE`

### ISSUE THREAD

**Issue by shivas** [lxn/walk#736]
This bug haunted for me for few hours thinking i'm doing something wrong. But looks like one-liner was missing.

PR with fix #735

**Comment by lxn** [comment]
Could you please provide a short repro that demonstrates the problem? It seems to me everything is working as expected.

**Comment by shivas** [comment]
@lxn there u go https://gist.github.com/shivas/59ad912e4c8a1150523096b9fa14fbcd

**Comment by shivas** [comment]
Btw, even though reproducible code doesn't have that, i noticed that if any other data-bound component value changed, it would save updated-actual combobox value. That gave me hint that there could be issue with event firing.

**Comment by shivas** [comment]
Then while debugging I found that message loop received this event: https://docs.microsoft.com/en-us/windows/win32/controls/cbn-selchange

**Comment by shivas** [comment]
@lxn any news about this? have you managed to reproduce it?

**Comment by lxn** [comment]
Yes, thanks for the repro code and PR. No idea how I managed to forget adding that.

**Comment by shivas** [comment]
@lxn thanks, name added
