### ISSUE TITLE
Seeking solutions for `progressionistor`

### ISSUE THREAD

**Issue by SwankyTigerYY** [lxn/walk#737]
examples/progressindicator.
`Go build` successful.but,it doesn't function properly.
I don't know how to get the wrong information.
Please recommend me a debugging method because `go run` doesn't work.
I will be very grateful.

**Comment by lxn** [comment]
That example needs to be rewritten. It still uses the no longer supported designer stuff.

**Comment by SwankyTigerYY** [comment]
Thank you. I see.
