### ISSUE TITLE
Can TabWidget append new TabLayout

### ISSUE THREAD

**Issue by huhuang03** [lxn/walk#738]
I have a TabWidget:
```
pages := []TabPage
tabLayout = TabWidget {
    Pages: pages
}
pages = append(pages, TabLayout {
    Title: "T1"
}
```

The append has no affect. Can TabWidget append new TabLayout?

**Comment by lxn** [comment]
I assume you meant `TabPage` when you wrote `TabLayout`.

Please check the Go docs about the `append` builtin. When adding to a slice with `append`, a new backing array gets allocated if required and `append` returns a slice that references the new array.

**Comment by huhuang03** [comment]
Thank you for your reply. I used the following code, but still no lucky.
```
package main

import (
	"fmt"

	. "github.com/lxn/walk/declarative"
)

func main() {
	tabs := TabWidget{
		Pages: []TabPage {
			TabPage {
				Title: "T1",
			},
		},
	}
	MainWindow{
		Title:   "SCREAMO",
		MinSize: Size{600, 400},
		Layout:  VBox{},
		Children: []Widget{
			PushButton {
				Text: "Test",
				OnClicked: func() {
					fmt.Println("test clicked")
					tabs.Pages = []TabPage {
						TabPage {
							Title: "t1",
						},
						TabPage {
							Title: "t2",
						},
					}
				},
			},
			tabs,
		},
	}.Run()
}
```

Should I manually call some `notifyUIUpdate` method?

**Comment by lxn** [comment]
Oh, I see. That's not going to work. Please have a look at how it is done in the `imageviewer` example.

**Comment by huhuang03** [comment]
Got it. Thank you!
