### ISSUE TITLE
recent commit broke groupbox rendering

### ISSUE THREAD

**Issue by zx2c4** [lxn/walk#739]
https://github.com/lxn/walk/commit/97e648c9f710630ce59c4617693baf14dcc103c8 broke rendering of groupboxes, despite the commit message indicating the opposite intention.

Before:
![image](https://user-images.githubusercontent.com/10643/98534911-7f7faa80-2285-11eb-9e26-79f9da40e676.png)

After:
![image](https://user-images.githubusercontent.com/10643/98534734-2f084d00-2285-11eb-8817-8d7309f2e6af.png)

What needs to be done to fix this? Does wireguard source need to change, or is this walk commit errant?

CC @lxn

**Comment by lxn** [comment]
Sorry for the trouble, I hope it's finally fixed now.

**Comment by zx2c4** [comment]
Seems to work! Thanks.
