### ISSUE TITLE
Can I set widget or container's width to match_parent

### ISSUE THREAD

**Issue by huhuang03** [lxn/walk#741]
After I dynamic add a TabLayout to TabWidget like this:
```
newPage, _ := walk.NewTabPage()
newPage.SetLayout(walk.NewVBoxLayout())
label, _ := walk.NewLabel(newPage)
label.SetText("T1")
tabs.Pages().Add(newPage)
```

But the `TabLayout` become very small, and so the `TabWidget`.

My question is: Can I set widget or container's width to as much as possible like `HSpacer VSpacer`. Thank you.

**Comment by lxn** [comment]
Please try `SetMinMaxSize`.

**Comment by huhuang03** [comment]
It's my fault. In my situation the real issue is that I forget to set Layout to a container..
