### ISSUE TITLE
May I know if there is any document?

### ISSUE THREAD

**Issue by DarcyNing** [lxn/walk#744]
May I know if there is any document?
1. Get started
2. Components infrastructure

**Comment by lxn** [comment]
Maybe have a look at [this](https://essential-go.programming-books.io/windows-gui-programming-944154630ac54def857caa8b50dd1b59).

Otherwise just check out the examples.

**Comment by alkanna** [comment]
Can we close this @lxn ?

**Comment by lxn** [comment]
Sure.
