### ISSUE TITLE
WPARAM(-1) ?

### ISSUE THREAD

**Issue by kubaraczkowski** [lxn/walk#762]
Hi,

Any clue how to call SendMessage with a wparam of -1?
EM_LINEFROMCHAR requires a value of -1 to get 'current' line position...

https://docs.microsoft.com/en-us/windows/win32/controls/em-linefromchar

Thanks in advance!

**Comment by lpintes** [comment]
Try uintptr(-1)

Dňa 28. 1. 2021 o 23:07 Kuba Raczkowski napísal(a):

**Comment by kubaraczkowski** [comment]
Yeah, tried that, it (logically?) goes `constant -1 overflows uintptr` :)

`0xffffffff` does the job, but feels... so 32bit :) Unless wparam is guaranteed to be 32bit even on 64b windows?

**Comment by lpintes** [comment]
Hmm I am not sure if -1 is encoded as 0xffff... all "f"?

If yes, then -1 = ^uintptr(0)

Dňa 29. 1. 2021 o 9:04 Kuba Raczkowski napísal(a):

**Comment by kubaraczkowski** [comment]
Ha, obviously, indeed! Thanks.
0xffff... is -1 in two's complement, I guess there's somewhere in there a cast to signed integer and that's what's checked.
