### ISSUE TITLE
Hello, when I  run "go build" , the test.exe was build，but it has cmd window , why？

### ISSUE THREAD

**Issue by nottellyou** [lxn/walk#772]
Hello, when I  run "go build" , the test.exe was build，but it has cmd window , why？
          Can you tell me where I operate wrong ?

        
![whereis wrong](https://user-images.githubusercontent.com/8598743/113114499-fc63ee80-923d-11eb-8abf-90139afdd986.png)

Thanks very much!

**Comment by spddl** [comment]
the cmd window can be used for debug purposes.

to remove it simply execute this command
`go build -ldflags="-H windowsgui"`

as described in [the readme](https://github.com/lxn/walk#build-app)

**Comment by nottellyou** [comment]
Thanks very much! I see it.
